// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enviornments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :exec

INSERT INTO environments (workspace_id, name)
VALUES ($1, $2)
`

type CreateEnvironmentParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Name        string      `db:"name" json:"name"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.Exec(ctx, createEnvironment, arg.WorkspaceID, arg.Name)
	return err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments
WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, workspace_id, name, created_at FROM environments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id pgtype.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentsByWorkspace = `-- name: GetEnvironmentsByWorkspace :many
SELECT id, workspace_id, name, created_at FROM environments
WHERE workspace_id = $1
`

func (q *Queries) GetEnvironmentsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, getEnvironmentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
