// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	WorkspaceID   pgtype.UUID      `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID      `db:"environment_id" json:"environment_id"`
	Label         string           `db:"label" json:"label"`
	KeyHash       string           `db:"key_hash" json:"key_hash"`
	KeyHint       string           `db:"key_hint" json:"key_hint"`
	IsRevoked     bool             `db:"is_revoked" json:"is_revoked"`
	RevokedAt     pgtype.Timestamp `db:"revoked_at" json:"revoked_at"`
	CreatedBy     pgtype.UUID      `db:"created_by" json:"created_by"`
	LastUsedAt    pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

type Environment struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	WorkspaceID pgtype.UUID      `db:"workspace_id" json:"workspace_id"`
	Name        string           `db:"name" json:"name"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Plan struct {
	ID                 pgtype.UUID      `db:"id" json:"id"`
	Name               string           `db:"name" json:"name"`
	NotifLimitMonth    int32            `db:"notif_limit_month" json:"notif_limit_month"`
	MembersLimit       int32            `db:"members_limit" json:"members_limit"`
	ApiKeysLimit       int32            `db:"api_keys_limit" json:"api_keys_limit"`
	LogRetentionDays   int32            `db:"log_retention_days" json:"log_retention_days"`
	OriginalPriceCents int32            `db:"original_price_cents" json:"original_price_cents"`
	PriceCents         int32            `db:"price_cents" json:"price_cents"`
	IsActive           bool             `db:"is_active" json:"is_active"`
	CreatedAt          pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	PasswordHash pgtype.Text      `db:"password_hash" json:"password_hash"`
	FullName     string           `db:"full_name" json:"full_name"`
	AuthProvider string           `db:"auth_provider" json:"auth_provider"`
	ProviderID   pgtype.Text      `db:"provider_id" json:"provider_id"`
	AvatarUrl    pgtype.Text      `db:"avatar_url" json:"avatar_url"`
	IsVerified   bool             `db:"is_verified" json:"is_verified"`
	IsActive     bool             `db:"is_active" json:"is_active"`
	LastLoginAt  pgtype.Timestamp `db:"last_login_at" json:"last_login_at"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Workspace struct {
	ID                pgtype.UUID      `db:"id" json:"id"`
	Name              string           `db:"name" json:"name"`
	Slug              string           `db:"slug" json:"slug"`
	PlanID            pgtype.UUID      `db:"plan_id" json:"plan_id"`
	NotifCountMonth   int32            `db:"notif_count_month" json:"notif_count_month"`
	BillingCycleStart pgtype.Date      `db:"billing_cycle_start" json:"billing_cycle_start"`
	CreatedAt         pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type WorkspaceMember struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	WorkspaceID pgtype.UUID      `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID      `db:"user_id" json:"user_id"`
	Role        string           `db:"role" json:"role"`
	InvitedBy   pgtype.UUID      `db:"invited_by" json:"invited_by"`
	JoinedAt    pgtype.Timestamp `db:"joined_at" json:"joined_at"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}
