// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password_hash, full_name, auth_provider, provider_id, avatar_url, is_verified, is_active, last_login_at, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AuthProvider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, password_hash, full_name, auth_provider, provider_id, avatar_url, is_verified, is_active, last_login_at, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AuthProvider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByProviderID = `-- name: FindUserByProviderID :one
SELECT id, email, password_hash, full_name, auth_provider, provider_id, avatar_url, is_verified, is_active, last_login_at, created_at, updated_at FROM users
WHERE auth_provider = $1
AND provider_id = $2
LIMIT 1
`

type FindUserByProviderIDParams struct {
	AuthProvider string      `db:"auth_provider" json:"auth_provider"`
	ProviderID   pgtype.Text `db:"provider_id" json:"provider_id"`
}

func (q *Queries) FindUserByProviderID(ctx context.Context, arg FindUserByProviderIDParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserByProviderID, arg.AuthProvider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AuthProvider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at    = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const upsertOAuthUser = `-- name: UpsertOAuthUser :one
INSERT INTO users (
    id,
    email,
    full_name,
    auth_provider,
    provider_id,
    avatar_url,
    is_verified
) VALUES (
    gen_random_uuid(),
    $1, $2, $3, $4, $5,
    true
)
ON CONFLICT (email) 
DO UPDATE SET 
    full_name     = EXCLUDED.full_name,
    avatar_url    = EXCLUDED.avatar_url,
    auth_provider      = EXCLUDED.auth_provider,
    provider_id   = EXCLUDED.provider_id,
    last_login_at = NOW(),
    updated_at    = NOW()
RETURNING id, email, password_hash, full_name, auth_provider, provider_id, avatar_url, is_verified, is_active, last_login_at, created_at, updated_at
`

type UpsertOAuthUserParams struct {
	Email        string      `db:"email" json:"email"`
	FullName     string      `db:"full_name" json:"full_name"`
	AuthProvider string      `db:"auth_provider" json:"auth_provider"`
	ProviderID   pgtype.Text `db:"provider_id" json:"provider_id"`
	AvatarUrl    pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpsertOAuthUser(ctx context.Context, arg UpsertOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertOAuthUser,
		arg.Email,
		arg.FullName,
		arg.AuthProvider,
		arg.ProviderID,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AuthProvider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
