// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members (id, workspace_id, user_id, role, joined_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW())
RETURNING id, workspace_id, user_id, role, invited_by, joined_at, created_at
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Role        string      `db:"role" json:"role"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1
AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM workspace_members
WHERE workspace_id = $1
AND user_id = $2
LIMIT 1
`

type GetMemberRoleParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getWorkspaceMemberByID = `-- name: GetWorkspaceMemberByID :one

select id, workspace_id, user_id, role, invited_by, joined_at, created_at from workspace_members where id = $1 limit 1
`

func (q *Queries) GetWorkspaceMemberByID(ctx context.Context, id pgtype.UUID) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberByID, id)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMemberByUserID = `-- name: GetWorkspaceMemberByUserID :one

select id, workspace_id, user_id, role, invited_by, joined_at, created_at from workspace_members where user_id = $1 limit 1
`

func (q *Queries) GetWorkspaceMemberByUserID(ctx context.Context, userID pgtype.UUID) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberByUserID, userID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT id, workspace_id, user_id, role, invited_by, joined_at, created_at FROM workspace_members
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceMember
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE workspace_members
SET role = $2
WHERE workspace_id = $1
AND user_id = $3
RETURNING id, workspace_id, user_id, role, invited_by, joined_at, created_at
`

type UpdateMemberRoleParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Role        string      `db:"role" json:"role"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.WorkspaceID, arg.Role, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}
