{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    {{- include "envoy-backend.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.provider.aws.service }}
      region: {{ .Values.secretStore.provider.aws.region }}
{{- end }}
