// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type AnalyticsRepository struct {
	mock.Mock
}

// CountActivityLogs provides a mock function with given fields: ctx, workspaceID, channel, status
func (_m *AnalyticsRepository) CountActivityLogs(ctx context.Context, workspaceID string, channel *string, status *string) (int64, error) {
	ret := _m.Called(ctx, workspaceID, channel, status)

	if len(ret) == 0 {
		panic("no return value specified for CountActivityLogs")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) (int64, error)); ok {
		return rf(ctx, workspaceID, channel, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) int64); ok {
		r0 = rf(ctx, workspaceID, channel, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string) error); ok {
		r1 = rf(ctx, workspaceID, channel, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAggregateMetrics provides a mock function with given fields: ctx, workspaceID, start, end
func (_m *AnalyticsRepository) GetAggregateMetrics(ctx context.Context, workspaceID string, start time.Time, end time.Time) (*domain.AggregateMetrics, error) {
	ret := _m.Called(ctx, workspaceID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregateMetrics")
	}

	var r0 *domain.AggregateMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (*domain.AggregateMetrics, error)); ok {
		return rf(ctx, workspaceID, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) *domain.AggregateMetrics); ok {
		r0 = rf(ctx, workspaceID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AggregateMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, workspaceID, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatencyTrend provides a mock function with given fields: ctx, workspaceID
func (_m *AnalyticsRepository) GetLatencyTrend(ctx context.Context, workspaceID string) ([]int32, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatencyTrend")
	}

	var r0 []int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]int32, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []int32); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProviderHealth provides a mock function with given fields: ctx, workspaceID
func (_m *AnalyticsRepository) GetProviderHealth(ctx context.Context, workspaceID string) ([]domain.ProviderHealth, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderHealth")
	}

	var r0 []domain.ProviderHealth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.ProviderHealth, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.ProviderHealth); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProviderHealth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTimeSeriesData provides a mock function with given fields: ctx, workspaceID, start, end, groupBy
func (_m *AnalyticsRepository) GetTimeSeriesData(ctx context.Context, workspaceID string, start time.Time, end time.Time, groupBy string) ([]domain.TimeSeriesData, error) {
	ret := _m.Called(ctx, workspaceID, start, end, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeSeriesData")
	}

	var r0 []domain.TimeSeriesData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string) ([]domain.TimeSeriesData, error)); ok {
		return rf(ctx, workspaceID, start, end, groupBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string) []domain.TimeSeriesData); ok {
		r0 = rf(ctx, workspaceID, start, end, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TimeSeriesData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, workspaceID, start, end, groupBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListActivityLogs provides a mock function with given fields: ctx, workspaceID, channel, status, limit, offset
func (_m *AnalyticsRepository) ListActivityLogs(ctx context.Context, workspaceID string, channel *string, status *string, limit int32, offset int32) ([]domain.ActivityLog, error) {
	ret := _m.Called(ctx, workspaceID, channel, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListActivityLogs")
	}

	var r0 []domain.ActivityLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) ([]domain.ActivityLog, error)); ok {
		return rf(ctx, workspaceID, channel, status, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) []domain.ActivityLog); ok {
		r0 = rf(ctx, workspaceID, channel, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ActivityLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string, int32, int32) error); ok {
		r1 = rf(ctx, workspaceID, channel, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsRepository creates a new instance of AnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsRepository {
	mock := &AnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
