// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/NIROOZbx/notification-engine/db/sqlc"
)

// APIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type APIKeyRepository struct {
	mock.Mock
}

// CountActiveKeys provides a mock function with given fields: ctx, workspaceID
func (_m *APIKeyRepository) CountActiveKeys(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveKeys")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (int64, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) int64); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, arg
func (_m *APIKeyRepository) Create(ctx context.Context, arg sqlc.CreateApiKeyParams) (sqlc.ApiKey, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 sqlc.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateApiKeyParams) (sqlc.ApiKey, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateApiKeyParams) sqlc.ApiKey); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.ApiKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateApiKeyParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, arg
func (_m *APIKeyRepository) Delete(ctx context.Context, arg sqlc.DeleteAPIKeyParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.DeleteAPIKeyParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.DeleteAPIKeyParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.DeleteAPIKeyParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEnvironment provides a mock function with given fields: ctx, id
func (_m *APIKeyRepository) GetEnvironment(ctx context.Context, id pgtype.UUID) (sqlc.Environment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvironment")
	}

	var r0 sqlc.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.Environment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.Environment); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Environment)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceWithPlan provides a mock function with given fields: ctx, id
func (_m *APIKeyRepository) GetWorkspaceWithPlan(ctx context.Context, id pgtype.UUID) (sqlc.GetWorkspaceWithPlanRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceWithPlan")
	}

	var r0 sqlc.GetWorkspaceWithPlanRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.GetWorkspaceWithPlanRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.GetWorkspaceWithPlanRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.GetWorkspaceWithPlanRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, arg
func (_m *APIKeyRepository) List(ctx context.Context, arg sqlc.ListAPIKeysByWorkspaceAndEnvParams) ([]sqlc.ListAPIKeysByWorkspaceAndEnvRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []sqlc.ListAPIKeysByWorkspaceAndEnvRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListAPIKeysByWorkspaceAndEnvParams) ([]sqlc.ListAPIKeysByWorkspaceAndEnvRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListAPIKeysByWorkspaceAndEnvParams) []sqlc.ListAPIKeysByWorkspaceAndEnvRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.ListAPIKeysByWorkspaceAndEnvRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.ListAPIKeysByWorkspaceAndEnvParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: ctx, arg
func (_m *APIKeyRepository) Revoke(ctx context.Context, arg sqlc.RevokeAPIKeyParams) (sqlc.RevokeAPIKeyRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 sqlc.RevokeAPIKeyRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.RevokeAPIKeyParams) (sqlc.RevokeAPIKeyRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.RevokeAPIKeyParams) sqlc.RevokeAPIKeyRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.RevokeAPIKeyRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.RevokeAPIKeyParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAndTouch provides a mock function with given fields: ctx, hash
func (_m *APIKeyRepository) ValidateAndTouch(ctx context.Context, hash string) (sqlc.ApiKey, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAndTouch")
	}

	var r0 sqlc.ApiKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.ApiKey, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.ApiKey); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Get(0).(sqlc.ApiKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPIKeyRepository creates a new instance of APIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIKeyRepository {
	mock := &APIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
