// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// LayoutRepo is an autogenerated mock type for the LayoutRepo type
type LayoutRepo struct {
	mock.Mock
}

// CountLayouts provides a mock function with given fields: ctx, workspaceID
func (_m *LayoutRepo) CountLayouts(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for CountLayouts")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (int64, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) int64); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, params
func (_m *LayoutRepo) Create(ctx context.Context, params domain.CreateLayoutParams) (*domain.Layout, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateLayoutParams) (*domain.Layout, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateLayoutParams) *domain.Layout); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateLayoutParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLayout provides a mock function with given fields: ctx, id, workspaceID
func (_m *LayoutRepo) DeleteLayout(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLayout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDefaultLayout provides a mock function with given fields: ctx, workspaceID
func (_m *LayoutRepo) GetDefaultLayout(ctx context.Context, workspaceID pgtype.UUID) (*domain.Layout, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultLayout")
	}

	var r0 *domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*domain.Layout, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *domain.Layout); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLayoutByID provides a mock function with given fields: ctx, id, workspaceID
func (_m *LayoutRepo) GetLayoutByID(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) (*domain.Layout, error) {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetLayoutByID")
	}

	var r0 *domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) (*domain.Layout, error)); ok {
		return rf(ctx, id, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) *domain.Layout); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, id, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, workspaceID
func (_m *LayoutRepo) List(ctx context.Context, workspaceID pgtype.UUID) ([]*domain.Layout, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]*domain.Layout, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []*domain.Layout); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetLayoutDefault provides a mock function with given fields: ctx, id, workspaceID
func (_m *LayoutRepo) SetLayoutDefault(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for SetLayoutDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLayout provides a mock function with given fields: ctx, params
func (_m *LayoutRepo) UpdateLayout(ctx context.Context, params domain.UpdateLayoutParams) (*domain.Layout, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLayout")
	}

	var r0 *domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateLayoutParams) (*domain.Layout, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateLayoutParams) *domain.Layout); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateLayoutParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLayoutRepo creates a new instance of LayoutRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLayoutRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LayoutRepo {
	mock := &LayoutRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
