// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/NIROOZbx/notification-engine/db/sqlc"
)

// PlanRepository is an autogenerated mock type for the PlanRepository type
type PlanRepository struct {
	mock.Mock
}

// GetAllPlans provides a mock function with given fields: ctx
func (_m *PlanRepository) GetAllPlans(ctx context.Context) ([]sqlc.Plan, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPlans")
	}

	var r0 []sqlc.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]sqlc.Plan, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []sqlc.Plan); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlanRepository creates a new instance of PlanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlanRepository {
	mock := &PlanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
