// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/NIROOZbx/notification-engine/engine/notification/core"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateNotificationLog provides a mock function with given fields: ctx, params
func (_m *Repository) CreateNotificationLog(ctx context.Context, params core.CreateLogParams) (*core.NotificationLog, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotificationLog")
	}

	var r0 *core.NotificationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, core.CreateLogParams) (*core.NotificationLog, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.CreateLogParams) *core.NotificationLog); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.CreateLogParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveChannelsByTemplateID provides a mock function with given fields: ctx, templateID
func (_m *Repository) GetActiveChannelsByTemplateID(ctx context.Context, templateID string) ([]core.TemplateChannel, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveChannelsByTemplateID")
	}

	var r0 []core.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]core.TemplateChannel, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []core.TemplateChannel); ok {
		r0 = rf(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannelConfigByID provides a mock function with given fields: ctx, channelConfigID, workspaceID
func (_m *Repository) GetChannelConfigByID(ctx context.Context, channelConfigID string, workspaceID string) (*core.ChannelConfig, error) {
	ret := _m.Called(ctx, channelConfigID, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelConfigByID")
	}

	var r0 *core.ChannelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*core.ChannelConfig, error)); ok {
		return rf(ctx, channelConfigID, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *core.ChannelConfig); ok {
		r0 = rf(ctx, channelConfigID, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ChannelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, channelConfigID, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContactByExternalUserAndChannel provides a mock function with given fields: ctx, workspaceID, envID, externalUserID, channel
func (_m *Repository) GetContactByExternalUserAndChannel(ctx context.Context, workspaceID string, envID string, externalUserID string, channel string) (*core.Contact, error) {
	ret := _m.Called(ctx, workspaceID, envID, externalUserID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetContactByExternalUserAndChannel")
	}

	var r0 *core.Contact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*core.Contact, error)); ok {
		return rf(ctx, workspaceID, envID, externalUserID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *core.Contact); ok {
		r0 = rf(ctx, workspaceID, envID, externalUserID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Contact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, envID, externalUserID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContactWithPreference provides a mock function with given fields: ctx, params
func (_m *Repository) GetContactWithPreference(ctx context.Context, params core.GetContactWithPreferenceParams) (*core.Contact, *core.Preference, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetContactWithPreference")
	}

	var r0 *core.Contact
	var r1 *core.Preference
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, core.GetContactWithPreferenceParams) (*core.Contact, *core.Preference, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, core.GetContactWithPreferenceParams) *core.Contact); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Contact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, core.GetContactWithPreferenceParams) *core.Preference); ok {
		r1 = rf(ctx, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*core.Preference)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, core.GetContactWithPreferenceParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetDefaultChannelConfig provides a mock function with given fields: ctx, workspaceID, channel
func (_m *Repository) GetDefaultChannelConfig(ctx context.Context, workspaceID string, channel string) (*core.ChannelConfig, error) {
	ret := _m.Called(ctx, workspaceID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultChannelConfig")
	}

	var r0 *core.ChannelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*core.ChannelConfig, error)); ok {
		return rf(ctx, workspaceID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *core.ChannelConfig); ok {
		r0 = rf(ctx, workspaceID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.ChannelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLayoutByID provides a mock function with given fields: ctx, layoutID, workspaceID
func (_m *Repository) GetLayoutByID(ctx context.Context, layoutID string, workspaceID string) (*core.Layout, error) {
	ret := _m.Called(ctx, layoutID, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetLayoutByID")
	}

	var r0 *core.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*core.Layout, error)); ok {
		return rf(ctx, layoutID, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *core.Layout); ok {
		r0 = rf(ctx, layoutID, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, layoutID, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotificationLogByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetNotificationLogByID(ctx context.Context, id string) (*core.NotificationLog, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationLogByID")
	}

	var r0 *core.NotificationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.NotificationLog, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.NotificationLog); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotificationLogByIdempotencyKey provides a mock function with given fields: ctx, key
func (_m *Repository) GetNotificationLogByIdempotencyKey(ctx context.Context, key string) (*core.NotificationLog, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationLogByIdempotencyKey")
	}

	var r0 *core.NotificationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.NotificationLog, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.NotificationLog); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreferencesBySubscriberAndChannel provides a mock function with given fields: ctx, subscriberID, channel, eventType
func (_m *Repository) GetPreferencesBySubscriberAndChannel(ctx context.Context, subscriberID string, channel string, eventType string) ([]core.Preference, error) {
	ret := _m.Called(ctx, subscriberID, channel, eventType)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferencesBySubscriberAndChannel")
	}

	var r0 []core.Preference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]core.Preference, error)); ok {
		return rf(ctx, subscriberID, channel, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []core.Preference); ok {
		r0 = rf(ctx, subscriberID, channel, eventType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Preference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, subscriberID, channel, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductionEnvironmentID provides a mock function with given fields: ctx, workspaceID
func (_m *Repository) GetProductionEnvironmentID(ctx context.Context, workspaceID string) (string, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductionEnvironmentID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplateByEventType provides a mock function with given fields: ctx, workspaceID, envID, eventType
func (_m *Repository) GetTemplateByEventType(ctx context.Context, workspaceID string, envID string, eventType string) (*core.Template, error) {
	ret := _m.Called(ctx, workspaceID, envID, eventType)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByEventType")
	}

	var r0 *core.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*core.Template, error)); ok {
		return rf(ctx, workspaceID, envID, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *core.Template); ok {
		r0 = rf(ctx, workspaceID, envID, eventType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, envID, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplateByID provides a mock function with given fields: ctx, workspaceID, templateID
func (_m *Repository) GetTemplateByID(ctx context.Context, workspaceID string, templateID string) (*core.Template, error) {
	ret := _m.Called(ctx, workspaceID, templateID)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByID")
	}

	var r0 *core.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*core.Template, error)); ok {
		return rf(ctx, workspaceID, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *core.Template); ok {
		r0 = rf(ctx, workspaceID, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplateChannel provides a mock function with given fields: ctx, templateID, channel
func (_m *Repository) GetTemplateChannel(ctx context.Context, templateID string, channel string) (*core.TemplateChannel, error) {
	ret := _m.Called(ctx, templateID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateChannel")
	}

	var r0 *core.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*core.TemplateChannel, error)); ok {
		return rf(ctx, templateID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *core.TemplateChannel); ok {
		r0 = rf(ctx, templateID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, templateID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTemplateWithChannel provides a mock function with given fields: ctx, templateID, workspaceID, channel
func (_m *Repository) GetTemplateWithChannel(ctx context.Context, templateID string, workspaceID string, channel string) (*core.Template, *core.TemplateChannel, error) {
	ret := _m.Called(ctx, templateID, workspaceID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateWithChannel")
	}

	var r0 *core.Template
	var r1 *core.TemplateChannel
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*core.Template, *core.TemplateChannel, error)); ok {
		return rf(ctx, templateID, workspaceID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *core.Template); ok {
		r0 = rf(ctx, templateID, workspaceID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) *core.TemplateChannel); ok {
		r1 = rf(ctx, templateID, workspaceID, channel)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*core.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, templateID, workspaceID, channel)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetWorkspaceOwners provides a mock function with given fields: ctx, workspaceID
func (_m *Repository) GetWorkspaceOwners(ctx context.Context, workspaceID string) ([]core.Contact, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceOwners")
	}

	var r0 []core.Contact
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]core.Contact, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []core.Contact); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Contact)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertNotificationAttempt provides a mock function with given fields: ctx, params
func (_m *Repository) InsertNotificationAttempt(ctx context.Context, params core.CreateAttemptParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InsertNotificationAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.CreateAttemptParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNotificationLog provides a mock function with given fields: ctx, params
func (_m *Repository) UpdateNotificationLog(ctx context.Context, params core.UpdateNotificationLogParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.UpdateNotificationLogParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNotificationStatus provides a mock function with given fields: ctx, id, status
func (_m *Repository) UpdateNotificationStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProviderMessageID provides a mock function with given fields: ctx, id, providerMessageID
func (_m *Repository) UpdateProviderMessageID(ctx context.Context, id string, providerMessageID string) error {
	ret := _m.Called(ctx, id, providerMessageID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProviderMessageID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, providerMessageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
