// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/NIROOZbx/notification-engine/engine/notification/core"
	mock "github.com/stretchr/testify/mock"
)

// SchedulerRepo is an autogenerated mock type for the SchedulerRepo type
type SchedulerRepo struct {
	mock.Mock
}

// GetDueRetryNotifications provides a mock function with given fields: ctx, limit
func (_m *SchedulerRepo) GetDueRetryNotifications(ctx context.Context, limit int) ([]*core.NotificationLog, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetDueRetryNotifications")
	}

	var r0 []*core.NotificationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*core.NotificationLog, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*core.NotificationLog); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDueScheduledNotifications provides a mock function with given fields: ctx, limit
func (_m *SchedulerRepo) GetDueScheduledNotifications(ctx context.Context, limit int) ([]*core.NotificationLog, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetDueScheduledNotifications")
	}

	var r0 []*core.NotificationLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*core.NotificationLog, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*core.NotificationLog); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.NotificationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotificationLog provides a mock function with given fields: ctx, params
func (_m *SchedulerRepo) UpdateNotificationLog(ctx context.Context, params core.UpdateNotificationLogParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.UpdateNotificationLogParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNotificationStatus provides a mock function with given fields: ctx, id, status
func (_m *SchedulerRepo) UpdateNotificationStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNotificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSchedulerRepo creates a new instance of SchedulerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerRepo {
	mock := &SchedulerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
