// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"

	sqlc "github.com/NIROOZbx/notification-engine/db/sqlc"
)

// SubscriberRepo is an autogenerated mock type for the SubscriberRepo type
type SubscriberRepo struct {
	mock.Mock
}

// CountSubscribers provides a mock function with given fields: ctx, workspaceID, environmentID
func (_m *SubscriberRepo) CountSubscribers(ctx context.Context, workspaceID pgtype.UUID, environmentID pgtype.UUID) (int64, error) {
	ret := _m.Called(ctx, workspaceID, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for CountSubscribers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) (int64, error)); ok {
		return rf(ctx, workspaceID, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) int64); ok {
		r0 = rf(ctx, workspaceID, environmentID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSubscriber provides a mock function with given fields: ctx, id, workspaceID
func (_m *SubscriberRepo) DeleteSubscriber(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscriber")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSubscriberByExternalIDAndChannel provides a mock function with given fields: ctx, workspaceID, envID, externalUserID, channel
func (_m *SubscriberRepo) GetSubscriberByExternalIDAndChannel(ctx context.Context, workspaceID string, envID string, externalUserID string, channel string) (*domain.Subscriber, error) {
	ret := _m.Called(ctx, workspaceID, envID, externalUserID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriberByExternalIDAndChannel")
	}

	var r0 *domain.Subscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*domain.Subscriber, error)); ok {
		return rf(ctx, workspaceID, envID, externalUserID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *domain.Subscriber); ok {
		r0 = rf(ctx, workspaceID, envID, externalUserID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Subscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, envID, externalUserID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPreferences provides a mock function with given fields: ctx, workspaceID, environmentID, externalUserID
func (_m *SubscriberRepo) ListPreferences(ctx context.Context, workspaceID pgtype.UUID, environmentID pgtype.UUID, externalUserID string) ([]*domain.UserPreference, error) {
	ret := _m.Called(ctx, workspaceID, environmentID, externalUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListPreferences")
	}

	var r0 []*domain.UserPreference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, string) ([]*domain.UserPreference, error)); ok {
		return rf(ctx, workspaceID, environmentID, externalUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, string) []*domain.UserPreference); ok {
		r0 = rf(ctx, workspaceID, environmentID, externalUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserPreference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID, string) error); ok {
		r1 = rf(ctx, workspaceID, environmentID, externalUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSubscribers provides a mock function with given fields: ctx, workspaceID, environmentID, limit, offset
func (_m *SubscriberRepo) ListSubscribers(ctx context.Context, workspaceID pgtype.UUID, environmentID pgtype.UUID, limit int32, offset int32) ([]*domain.Subscriber, error) {
	ret := _m.Called(ctx, workspaceID, environmentID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListSubscribers")
	}

	var r0 []*domain.Subscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, int32, int32) ([]*domain.Subscriber, error)); ok {
		return rf(ctx, workspaceID, environmentID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, int32, int32) []*domain.Subscriber); ok {
		r0 = rf(ctx, workspaceID, environmentID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Subscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID, int32, int32) error); ok {
		r1 = rf(ctx, workspaceID, environmentID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertPreference provides a mock function with given fields: ctx, params
func (_m *SubscriberRepo) UpsertPreference(ctx context.Context, params sqlc.UpsertUserPreferenceParams) (*domain.UserPreference, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPreference")
	}

	var r0 *domain.UserPreference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertUserPreferenceParams) (*domain.UserPreference, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertUserPreferenceParams) *domain.UserPreference); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPreference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.UpsertUserPreferenceParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertSubscriber provides a mock function with given fields: ctx, params
func (_m *SubscriberRepo) UpsertSubscriber(ctx context.Context, params sqlc.UpsertUserContactInfoParams) (*domain.Subscriber, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSubscriber")
	}

	var r0 *domain.Subscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertUserContactInfoParams) (*domain.Subscriber, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertUserContactInfoParams) *domain.Subscriber); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Subscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.UpsertUserContactInfoParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriberRepo creates a new instance of SubscriberRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriberRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriberRepo {
	mock := &SubscriberRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
