// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// TemplateRepository is an autogenerated mock type for the TemplateRepository type
type TemplateRepository struct {
	mock.Mock
}

// CountTemplates provides a mock function with given fields: ctx, workspaceID
func (_m *TemplateRepository) CountTemplates(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for CountTemplates")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (int64, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) int64); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, params
func (_m *TemplateRepository) Create(ctx context.Context, params domain.CreateTemplateParams) (*domain.Template, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateParams) (*domain.Template, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateParams) *domain.Template); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateTemplateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateChannel provides a mock function with given fields: ctx, params
func (_m *TemplateRepository) CreateChannel(ctx context.Context, params domain.CreateTemplateChannelParams) (*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 *domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateChannelParams) (*domain.TemplateChannel, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateChannelParams) *domain.TemplateChannel); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateTemplateChannelParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, workspaceID
func (_m *TemplateRepository) Delete(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChannel provides a mock function with given fields: ctx, id, templateID
func (_m *TemplateRepository) DeleteChannel(ctx context.Context, id pgtype.UUID, templateID pgtype.UUID) error {
	ret := _m.Called(ctx, id, templateID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, templateID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByEventType provides a mock function with given fields: ctx, workspaceID, envID, eventType
func (_m *TemplateRepository) GetByEventType(ctx context.Context, workspaceID pgtype.UUID, envID pgtype.UUID, eventType string) (*domain.Template, error) {
	ret := _m.Called(ctx, workspaceID, envID, eventType)

	if len(ret) == 0 {
		panic("no return value specified for GetByEventType")
	}

	var r0 *domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, string) (*domain.Template, error)); ok {
		return rf(ctx, workspaceID, envID, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, string) *domain.Template); ok {
		r0 = rf(ctx, workspaceID, envID, eventType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID, string) error); ok {
		r1 = rf(ctx, workspaceID, envID, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id, workspaceID
func (_m *TemplateRepository) GetByID(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) (*domain.Template, error) {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) (*domain.Template, error)); ok {
		return rf(ctx, id, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) *domain.Template); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, id, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannelByID provides a mock function with given fields: ctx, id
func (_m *TemplateRepository) GetChannelByID(ctx context.Context, id pgtype.UUID) (*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelByID")
	}

	var r0 *domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*domain.TemplateChannel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *domain.TemplateChannel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannelByTemplateAndChannel provides a mock function with given fields: ctx, templateID, channel
func (_m *TemplateRepository) GetChannelByTemplateAndChannel(ctx context.Context, templateID pgtype.UUID, channel string) (*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, templateID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelByTemplateAndChannel")
	}

	var r0 *domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) (*domain.TemplateChannel, error)); ok {
		return rf(ctx, templateID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) *domain.TemplateChannel); ok {
		r0 = rf(ctx, templateID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, string) error); ok {
		r1 = rf(ctx, templateID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasActiveChannels provides a mock function with given fields: ctx, templateID
func (_m *TemplateRepository) HasActiveChannels(ctx context.Context, templateID pgtype.UUID) (bool, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveChannels")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (bool, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) bool); ok {
		r0 = rf(ctx, templateID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, workspaceID, envID
func (_m *TemplateRepository) List(ctx context.Context, workspaceID pgtype.UUID, envID pgtype.UUID) ([]*domain.Template, error) {
	ret := _m.Called(ctx, workspaceID, envID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) ([]*domain.Template, error)); ok {
		return rf(ctx, workspaceID, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) []*domain.Template); ok {
		r0 = rf(ctx, workspaceID, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListChannels provides a mock function with given fields: ctx, templateID
func (_m *TemplateRepository) ListChannels(ctx context.Context, templateID pgtype.UUID) ([]*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, templateID)

	if len(ret) == 0 {
		panic("no return value specified for ListChannels")
	}

	var r0 []*domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]*domain.TemplateChannel, error)); ok {
		return rf(ctx, templateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []*domain.TemplateChannel); ok {
		r0 = rf(ctx, templateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, templateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, params
func (_m *TemplateRepository) Update(ctx context.Context, params domain.UpdateTemplateParams) (*domain.Template, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateParams) (*domain.Template, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateParams) *domain.Template); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateTemplateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChannel provides a mock function with given fields: ctx, params
func (_m *TemplateRepository) UpdateChannel(ctx context.Context, params domain.UpdateTemplateChannelParams) (*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChannel")
	}

	var r0 *domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateChannelParams) (*domain.TemplateChannel, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateChannelParams) *domain.TemplateChannel); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateTemplateChannelParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTemplateRepository creates a new instance of TemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateRepository {
	mock := &TemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
