// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	sqlc "github.com/NIROOZbx/notification-engine/db/sqlc"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *UserRepository) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) (sqlc.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) sqlc.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) FindUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) FindUserByID(ctx context.Context, id pgtype.UUID) (sqlc.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByProviderID provides a mock function with given fields: ctx, arg
func (_m *UserRepository) FindUserByProviderID(ctx context.Context, arg sqlc.FindUserByProviderIDParams) (sqlc.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByProviderID")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.FindUserByProviderIDParams) (sqlc.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.FindUserByProviderIDParams) sqlc.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.FindUserByProviderIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthContextByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetAuthContextByEmail(ctx context.Context, email string) (sqlc.GetAuthContextByEmailRow, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthContextByEmail")
	}

	var r0 sqlc.GetAuthContextByEmailRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.GetAuthContextByEmailRow, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.GetAuthContextByEmailRow); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlc.GetAuthContextByEmailRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserWithWorkspace provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetUserWithWorkspace(ctx context.Context, id pgtype.UUID) (sqlc.GetUserWithWorkspaceRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithWorkspace")
	}

	var r0 sqlc.GetUserWithWorkspaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.GetUserWithWorkspaceRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.GetUserWithWorkspaceRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.GetUserWithWorkspaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkUserAsVerified provides a mock function with given fields: ctx, id
func (_m *UserRepository) MarkUserAsVerified(ctx context.Context, id pgtype.UUID) (sqlc.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserAsVerified")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertOAuthUser provides a mock function with given fields: ctx, arg
func (_m *UserRepository) UpsertOAuthUser(ctx context.Context, arg sqlc.UpsertOAuthUserParams) (sqlc.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOAuthUser")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertOAuthUserParams) (sqlc.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpsertOAuthUserParams) sqlc.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.UpsertOAuthUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
