// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	repositories "github.com/NIROOZbx/notification-engine/internal/repositories"

	sqlc "github.com/NIROOZbx/notification-engine/db/sqlc"
)

// WorkspaceRepository is an autogenerated mock type for the WorkspaceRepository type
type WorkspaceRepository struct {
	mock.Mock
}

// Atomic provides a mock function with given fields: ctx, fn
func (_m *WorkspaceRepository) Atomic(ctx context.Context, fn func(repositories.WorkspaceRepository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Atomic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(repositories.WorkspaceRepository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateEnvironment provides a mock function with given fields: ctx, arg
func (_m *WorkspaceRepository) CreateEnvironment(ctx context.Context, arg sqlc.CreateEnvironmentParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEnvironment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateEnvironmentParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWorkspace provides a mock function with given fields: ctx, arg
func (_m *WorkspaceRepository) CreateWorkspace(ctx context.Context, arg sqlc.CreateWorkspaceParams) (sqlc.Workspace, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkspace")
	}

	var r0 sqlc.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateWorkspaceParams) (sqlc.Workspace, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateWorkspaceParams) sqlc.Workspace); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Workspace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateWorkspaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWorkspaceMember provides a mock function with given fields: ctx, arg
func (_m *WorkspaceRepository) CreateWorkspaceMember(ctx context.Context, arg sqlc.CreateWorkspaceMemberParams) (sqlc.WorkspaceMember, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkspaceMember")
	}

	var r0 sqlc.WorkspaceMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateWorkspaceMemberParams) (sqlc.WorkspaceMember, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateWorkspaceMemberParams) sqlc.WorkspaceMember); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.WorkspaceMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateWorkspaceMemberParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWorkspace provides a mock function with given fields: ctx, id
func (_m *WorkspaceRepository) DeleteWorkspace(ctx context.Context, id pgtype.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWorkspaceMember provides a mock function with given fields: ctx, arg
func (_m *WorkspaceRepository) DeleteWorkspaceMember(ctx context.Context, arg sqlc.DeleteWorkspaceMemberParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspaceMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.DeleteWorkspaceMemberParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindWorkspaceByID provides a mock function with given fields: ctx, id
func (_m *WorkspaceRepository) FindWorkspaceByID(ctx context.Context, id pgtype.UUID) (sqlc.Workspace, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindWorkspaceByID")
	}

	var r0 sqlc.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.Workspace, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.Workspace); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.Workspace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemberRole provides a mock function with given fields: ctx, arg
func (_m *WorkspaceRepository) GetMemberRole(ctx context.Context, arg sqlc.GetMemberRoleParams) (string, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetMemberRoleParams) (string, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.GetMemberRoleParams) string); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.GetMemberRoleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOwnerCount provides a mock function with given fields: ctx, workspaceID
func (_m *WorkspaceRepository) GetOwnerCount(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnerCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (int64, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) int64); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceBySlug provides a mock function with given fields: ctx, slug
func (_m *WorkspaceRepository) GetWorkspaceBySlug(ctx context.Context, slug string) (sqlc.Workspace, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceBySlug")
	}

	var r0 sqlc.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.Workspace, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.Workspace); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(sqlc.Workspace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceMemberByUserID provides a mock function with given fields: ctx, userID
func (_m *WorkspaceRepository) GetWorkspaceMemberByUserID(ctx context.Context, userID pgtype.UUID) (sqlc.WorkspaceMember, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceMemberByUserID")
	}

	var r0 sqlc.WorkspaceMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.WorkspaceMember, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.WorkspaceMember); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(sqlc.WorkspaceMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceMembers provides a mock function with given fields: ctx, workspaceID
func (_m *WorkspaceRepository) GetWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]sqlc.GetWorkspaceMembersWithDetailsRow, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceMembers")
	}

	var r0 []sqlc.GetWorkspaceMembersWithDetailsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]sqlc.GetWorkspaceMembersWithDetailsRow, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []sqlc.GetWorkspaceMembersWithDetailsRow); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.GetWorkspaceMembersWithDetailsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceWithPlan provides a mock function with given fields: ctx, id
func (_m *WorkspaceRepository) GetWorkspaceWithPlan(ctx context.Context, id pgtype.UUID) (sqlc.GetWorkspaceWithPlanNameRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceWithPlan")
	}

	var r0 sqlc.GetWorkspaceWithPlanNameRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (sqlc.GetWorkspaceWithPlanNameRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) sqlc.GetWorkspaceWithPlanNameRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.GetWorkspaceWithPlanNameRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMemberRole provides a mock function with given fields: ctx, arg
func (_m *WorkspaceRepository) UpdateMemberRole(ctx context.Context, arg sqlc.UpdateMemberRoleParams) (sqlc.WorkspaceMember, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 sqlc.WorkspaceMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateMemberRoleParams) (sqlc.WorkspaceMember, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateMemberRoleParams) sqlc.WorkspaceMember); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.WorkspaceMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.UpdateMemberRoleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWorkspaceName provides a mock function with given fields: ctx, arg
func (_m *WorkspaceRepository) UpdateWorkspaceName(ctx context.Context, arg sqlc.UpdateWorkspaceNameParams) (sqlc.Workspace, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspaceName")
	}

	var r0 sqlc.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateWorkspaceNameParams) (sqlc.Workspace, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateWorkspaceNameParams) sqlc.Workspace); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.Workspace)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.UpdateWorkspaceNameParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorkspaceRepository creates a new instance of WorkspaceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceRepository {
	mock := &WorkspaceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
