ALTER TABLE plans
ADD COLUMN email_limit_month INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN sms_limit_month   INTEGER NOT NULL DEFAULT 100,
ADD COLUMN push_limit_month  INTEGER NOT NULL DEFAULT 5000,
ADD COLUMN slack_limit_month    INTEGER NOT NULL DEFAULT 500,
ADD COLUMN whatsapp_limit_month INTEGER NOT NULL DEFAULT 100,
ADD COLUMN webhook_limit_month  INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN in_app_limit_month   INTEGER NOT NULL DEFAULT 5000;

ALTER TABLE plans
DROP COLUMN notif_limit_month;
