// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLogs = `-- name: CountActivityLogs :one
SELECT COUNT(*)
FROM notification_logs
WHERE workspace_id = $1
  AND ($2::text IS NULL OR channel = $2)
  AND ($3::text IS NULL OR delivery_status = $3)
`

type CountActivityLogsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Channel     pgtype.Text `db:"channel" json:"channel"`
	Status      pgtype.Text `db:"status" json:"status"`
}

func (q *Queries) CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogs, arg.WorkspaceID, arg.Channel, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAggregateMetrics = `-- name: GetAggregateMetrics :many
SELECT nl.channel,
    na.provider,
    COUNT(*) AS total_count,
    COUNT(*) FILTER (
        WHERE nl.delivery_status = 'delivered'
    ) AS delivered_count,
    COUNT(*) FILTER (
        WHERE nl.delivery_status IN ('failed', 'bounced', 'complained')
            OR nl.delivery_status = 'failed'
    ) AS failed_count
FROM notification_logs nl
    LEFT JOIN notification_attempts na ON nl.id = na.notification_log_id
WHERE nl.workspace_id = $1
    AND nl.created_at >= $2
    AND nl.created_at <= $3
GROUP BY nl.channel,
    na.provider
`

type GetAggregateMetricsParams struct {
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `db:"created_at_2" json:"created_at_2"`
}

type GetAggregateMetricsRow struct {
	Channel        string      `db:"channel" json:"channel"`
	Provider       pgtype.Text `db:"provider" json:"provider"`
	TotalCount     int64       `db:"total_count" json:"total_count"`
	DeliveredCount int64       `db:"delivered_count" json:"delivered_count"`
	FailedCount    int64       `db:"failed_count" json:"failed_count"`
}

func (q *Queries) GetAggregateMetrics(ctx context.Context, arg GetAggregateMetricsParams) ([]GetAggregateMetricsRow, error) {
	rows, err := q.db.Query(ctx, getAggregateMetrics, arg.WorkspaceID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAggregateMetricsRow
	for rows.Next() {
		var i GetAggregateMetricsRow
		if err := rows.Scan(
			&i.Channel,
			&i.Provider,
			&i.TotalCount,
			&i.DeliveredCount,
			&i.FailedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatencyTrend = `-- name: GetLatencyTrend :many
SELECT na.duration_ms
FROM notification_attempts na
    INNER JOIN notification_logs nl ON na.notification_log_id = nl.id
WHERE nl.workspace_id = $1
ORDER BY na.attempted_at DESC
LIMIT 20
`

func (q *Queries) GetLatencyTrend(ctx context.Context, workspaceID pgtype.UUID) ([]pgtype.Int4, error) {
	rows, err := q.db.Query(ctx, getLatencyTrend, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int4
	for rows.Next() {
		var duration_ms pgtype.Int4
		if err := rows.Scan(&duration_ms); err != nil {
			return nil, err
		}
		items = append(items, duration_ms)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderHealth = `-- name: GetProviderHealth :many
SELECT na.provider,
    AVG(na.duration_ms)::int AS avg_latency,
    MAX(na.attempted_at)::timestamptz AS last_sync
FROM notification_attempts na
    INNER JOIN notification_logs nl ON na.notification_log_id = nl.id
WHERE nl.workspace_id = $1
    AND na.attempted_at >= NOW() - INTERVAL '24 hours'
GROUP BY na.provider
ORDER BY last_sync DESC
`

type GetProviderHealthRow struct {
	Provider   string             `db:"provider" json:"provider"`
	AvgLatency int32              `db:"avg_latency" json:"avg_latency"`
	LastSync   pgtype.Timestamptz `db:"last_sync" json:"last_sync"`
}

func (q *Queries) GetProviderHealth(ctx context.Context, workspaceID pgtype.UUID) ([]GetProviderHealthRow, error) {
	rows, err := q.db.Query(ctx, getProviderHealth, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProviderHealthRow
	for rows.Next() {
		var i GetProviderHealthRow
		if err := rows.Scan(&i.Provider, &i.AvgLatency, &i.LastSync); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeSeriesData = `-- name: GetTimeSeriesData :many
SELECT CASE
        WHEN $4::text = 'hour' THEN date_trunc('hour', created_at)
        WHEN $4::text = 'week' THEN date_trunc('week', created_at)
        WHEN $4::text = 'month' THEN date_trunc('month', created_at)
        ELSE date_trunc('day', created_at)
    END::timestamptz AS time_bucket,
    count(*) FILTER (
        WHERE nl.delivery_status = 'sent'
    ) as total_sent,
    COUNT(*) FILTER (
        WHERE nl.delivery_status IN ('failed', 'bounced')
            OR nl.status = 'failed'
    ) as total_failed,
    count(*) FILTER (
        WHERE nl.delivery_status = 'delivered'
    ) as total_delivered
FROM notification_logs as nl
WHERE nl.workspace_id = $1
    AND nl.created_at >= $2
    AND nl.created_at <= $3
GROUP BY time_bucket
ORDER BY time_bucket
`

type GetTimeSeriesDataParams struct {
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `db:"created_at_2" json:"created_at_2"`
	GroupBy     string             `db:"group_by" json:"group_by"`
}

type GetTimeSeriesDataRow struct {
	TimeBucket     pgtype.Timestamptz `db:"time_bucket" json:"time_bucket"`
	TotalSent      int64              `db:"total_sent" json:"total_sent"`
	TotalFailed    int64              `db:"total_failed" json:"total_failed"`
	TotalDelivered int64              `db:"total_delivered" json:"total_delivered"`
}

func (q *Queries) GetTimeSeriesData(ctx context.Context, arg GetTimeSeriesDataParams) ([]GetTimeSeriesDataRow, error) {
	rows, err := q.db.Query(ctx, getTimeSeriesData,
		arg.WorkspaceID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.GroupBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTimeSeriesDataRow
	for rows.Next() {
		var i GetTimeSeriesDataRow
		if err := rows.Scan(
			&i.TimeBucket,
			&i.TotalSent,
			&i.TotalFailed,
			&i.TotalDelivered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT 
    nl.id,
    nl.channel,
    nl.delivery_status,
    nl.recipient,
    nl.error_message,
    nl.template_id,
    nl.external_user_id,
    nl.trigger_data,
    nl.attempt_count,
    nl.provider_message_id,
    nl.provider_response,
    nl.created_at,
    nl.sent_at,
    nl.delivered_at,
    nl.failed_at,
    t.name as template_name,
    na.provider,
    na.duration_ms
FROM notification_logs nl
LEFT JOIN notification_attempts na ON nl.id = na.notification_log_id
LEFT JOIN templates t ON nl.template_id = t.id
WHERE nl.workspace_id = $1
  AND ($4::text IS NULL OR nl.channel = $4)
  AND ($5::text IS NULL OR nl.delivery_status = $5)
ORDER BY nl.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Limit       int32       `db:"limit" json:"limit"`
	Offset      int32       `db:"offset" json:"offset"`
	Channel     pgtype.Text `db:"channel" json:"channel"`
	Status      pgtype.Text `db:"status" json:"status"`
}

type ListActivityLogsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Channel           string             `db:"channel" json:"channel"`
	DeliveryStatus    pgtype.Text        `db:"delivery_status" json:"delivery_status"`
	Recipient         string             `db:"recipient" json:"recipient"`
	ErrorMessage      pgtype.Text        `db:"error_message" json:"error_message"`
	TemplateID        pgtype.UUID        `db:"template_id" json:"template_id"`
	ExternalUserID    string             `db:"external_user_id" json:"external_user_id"`
	TriggerData       []byte             `db:"trigger_data" json:"trigger_data"`
	AttemptCount      int32              `db:"attempt_count" json:"attempt_count"`
	ProviderMessageID pgtype.Text        `db:"provider_message_id" json:"provider_message_id"`
	ProviderResponse  pgtype.Text        `db:"provider_response" json:"provider_response"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SentAt            pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt          pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	TemplateName      pgtype.Text        `db:"template_name" json:"template_name"`
	Provider          pgtype.Text        `db:"provider" json:"provider"`
	DurationMs        pgtype.Int4        `db:"duration_ms" json:"duration_ms"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogs,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.Channel,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityLogsRow
	for rows.Next() {
		var i ListActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.DeliveryStatus,
			&i.Recipient,
			&i.ErrorMessage,
			&i.TemplateID,
			&i.ExternalUserID,
			&i.TriggerData,
			&i.AttemptCount,
			&i.ProviderMessageID,
			&i.ProviderResponse,
			&i.CreatedAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.TemplateName,
			&i.Provider,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
