// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT COUNT(*) FROM api_keys 
WHERE workspace_id = $1 
AND is_revoked = FALSE
AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) CountActiveAPIKeys(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeys, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (
        workspace_id,
        environment_id,
        label,
        key_hash,
        key_hint,
        created_by,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5, $6,$7)
RETURNING id, workspace_id, environment_id, label, key_hash, key_hint, is_revoked, revoked_at, created_by, last_used_at, created_at, updated_at, expires_at
`

type CreateApiKeyParams struct {
	WorkspaceID   pgtype.UUID      `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID      `db:"environment_id" json:"environment_id"`
	Label         string           `db:"label" json:"label"`
	KeyHash       string           `db:"key_hash" json:"key_hash"`
	KeyHint       string           `db:"key_hint" json:"key_hint"`
	CreatedBy     pgtype.UUID      `db:"created_by" json:"created_by"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.Label,
		arg.KeyHash,
		arg.KeyHint,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.Label,
		&i.KeyHash,
		&i.KeyHint,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys
WHERE id = $1
    AND workspace_id = $2
`

type DeleteAPIKeyParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, workspace_id, environment_id, label, key_hash, key_hint, is_revoked, revoked_at, created_by, last_used_at, created_at, updated_at, expires_at
FROM api_keys
WHERE id = $1
    AND workspace_id = $2
`

type GetAPIKeyByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, arg.ID, arg.WorkspaceID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.Label,
		&i.KeyHash,
		&i.KeyHint,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPIKeysByWorkspaceAndEnv = `-- name: ListAPIKeysByWorkspaceAndEnv :many
SELECT
    id,
    workspace_id,
    environment_id,
    label,
    key_hint,
    is_revoked,
    revoked_at,
    expires_at,
    created_by,
    last_used_at,
    created_at,
    updated_at
FROM api_keys
WHERE workspace_id = $1
AND environment_id = $2
ORDER BY created_at DESC
`

type ListAPIKeysByWorkspaceAndEnvParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

type ListAPIKeysByWorkspaceAndEnvRow struct {
	ID            pgtype.UUID      `db:"id" json:"id"`
	WorkspaceID   pgtype.UUID      `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID      `db:"environment_id" json:"environment_id"`
	Label         string           `db:"label" json:"label"`
	KeyHint       string           `db:"key_hint" json:"key_hint"`
	IsRevoked     bool             `db:"is_revoked" json:"is_revoked"`
	RevokedAt     pgtype.Timestamp `db:"revoked_at" json:"revoked_at"`
	ExpiresAt     pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedBy     pgtype.UUID      `db:"created_by" json:"created_by"`
	LastUsedAt    pgtype.Timestamp `db:"last_used_at" json:"last_used_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAPIKeysByWorkspaceAndEnv(ctx context.Context, arg ListAPIKeysByWorkspaceAndEnvParams) ([]ListAPIKeysByWorkspaceAndEnvRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByWorkspaceAndEnv, arg.WorkspaceID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByWorkspaceAndEnvRow
	for rows.Next() {
		var i ListAPIKeysByWorkspaceAndEnvRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.Label,
			&i.KeyHint,
			&i.IsRevoked,
			&i.RevokedAt,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET is_revoked = TRUE,
    revoked_at = NOW()
WHERE id = $1
    AND workspace_id = $2
    AND is_revoked=false
RETURNING id,is_revoked, revoked_at
`

type RevokeAPIKeyParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

type RevokeAPIKeyRow struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	IsRevoked bool             `db:"is_revoked" json:"is_revoked"`
	RevokedAt pgtype.Timestamp `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (RevokeAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.WorkspaceID)
	var i RevokeAPIKeyRow
	err := row.Scan(&i.ID, &i.IsRevoked, &i.RevokedAt)
	return i, err
}

const validateAndTouchAPIKey = `-- name: ValidateAndTouchAPIKey :one
UPDATE api_keys
SET last_used_at = NOW()
WHERE key_hash = $1
    AND is_revoked = FALSE
    AND (expires_at IS NULL OR expires_at > NOW())
RETURNING id, workspace_id, environment_id, label
`

type ValidateAndTouchAPIKeyRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
	Label         string      `db:"label" json:"label"`
}

func (q *Queries) ValidateAndTouchAPIKey(ctx context.Context, keyHash string) (ValidateAndTouchAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, validateAndTouchAPIKey, keyHash)
	var i ValidateAndTouchAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.Label,
	)
	return i, err
}
