// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveProvidersForChannel = `-- name: CountActiveProvidersForChannel :one
SELECT COUNT(*) FROM channel_configs 
WHERE workspace_id = $1 AND channel = $2 AND deleted_at IS NULL
`

type CountActiveProvidersForChannelParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Channel     string      `db:"channel" json:"channel"`
}

func (q *Queries) CountActiveProvidersForChannel(ctx context.Context, arg CountActiveProvidersForChannelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProvidersForChannel, arg.WorkspaceID, arg.Channel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannelConfig = `-- name: CreateChannelConfig :one
INSERT INTO channel_configs (
    workspace_id,
    channel,
    provider,
    display_name,
    credentials,
    is_active,
    is_default
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at, deleted_at
`

type CreateChannelConfigParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Channel     string      `db:"channel" json:"channel"`
	Provider    string      `db:"provider" json:"provider"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Credentials string      `db:"credentials" json:"credentials"`
	IsActive    bool        `db:"is_active" json:"is_active"`
	IsDefault   bool        `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateChannelConfig(ctx context.Context, arg CreateChannelConfigParams) (ChannelConfig, error) {
	row := q.db.QueryRow(ctx, createChannelConfig,
		arg.WorkspaceID,
		arg.Channel,
		arg.Provider,
		arg.DisplayName,
		arg.Credentials,
		arg.IsActive,
		arg.IsDefault,
	)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Provider,
		&i.DisplayName,
		&i.Credentials,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelConfigByID = `-- name: GetChannelConfigByID :one
SELECT id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at, deleted_at FROM channel_configs 
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type GetChannelConfigByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetChannelConfigByID(ctx context.Context, arg GetChannelConfigByIDParams) (ChannelConfig, error) {
	row := q.db.QueryRow(ctx, getChannelConfigByID, arg.ID, arg.WorkspaceID)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Provider,
		&i.DisplayName,
		&i.Credentials,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelConfigByIDAndWorkspace = `-- name: GetChannelConfigByIDAndWorkspace :one

SELECT id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at, deleted_at FROM channel_configs
WHERE id=$1 and workspace_id =$2
`

type GetChannelConfigByIDAndWorkspaceParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetChannelConfigByIDAndWorkspace(ctx context.Context, arg GetChannelConfigByIDAndWorkspaceParams) (ChannelConfig, error) {
	row := q.db.QueryRow(ctx, getChannelConfigByIDAndWorkspace, arg.ID, arg.WorkspaceID)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Provider,
		&i.DisplayName,
		&i.Credentials,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDefaultChannelConfig = `-- name: GetDefaultChannelConfig :one
SELECT id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at, deleted_at FROM channel_configs
WHERE workspace_id = $1 AND channel = $2 AND is_default = true AND deleted_at IS NULL
LIMIT 1
`

type GetDefaultChannelConfigParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Channel     string      `db:"channel" json:"channel"`
}

func (q *Queries) GetDefaultChannelConfig(ctx context.Context, arg GetDefaultChannelConfigParams) (ChannelConfig, error) {
	row := q.db.QueryRow(ctx, getDefaultChannelConfig, arg.WorkspaceID, arg.Channel)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Provider,
		&i.DisplayName,
		&i.Credentials,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProviderForWorker = `-- name: GetProviderForWorker :one
SELECT id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at, deleted_at FROM channel_configs 
WHERE id = $1 AND workspace_id = $2
`

type GetProviderForWorkerParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetProviderForWorker(ctx context.Context, arg GetProviderForWorkerParams) (ChannelConfig, error) {
	row := q.db.QueryRow(ctx, getProviderForWorker, arg.ID, arg.WorkspaceID)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Provider,
		&i.DisplayName,
		&i.Credentials,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChannelConfigs = `-- name: ListChannelConfigs :many
SELECT id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at, deleted_at FROM channel_configs
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY channel, created_at DESC
`

func (q *Queries) ListChannelConfigs(ctx context.Context, workspaceID pgtype.UUID) ([]ChannelConfig, error) {
	rows, err := q.db.Query(ctx, listChannelConfigs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelConfig
	for rows.Next() {
		var i ChannelConfig
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Channel,
			&i.Provider,
			&i.DisplayName,
			&i.Credentials,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProviderOverride = `-- name: RemoveProviderOverride :exec
UPDATE template_channels tc
SET channel_config_id = NULL 
from templates t WHERE tc.template_id=t.id and tc.channel_config_id=$1
and t.workspace_id=$2
`

type RemoveProviderOverrideParams struct {
	ChannelConfigID pgtype.UUID `db:"channel_config_id" json:"channel_config_id"`
	WorkspaceID     pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) RemoveProviderOverride(ctx context.Context, arg RemoveProviderOverrideParams) error {
	_, err := q.db.Exec(ctx, removeProviderOverride, arg.ChannelConfigID, arg.WorkspaceID)
	return err
}

const setChannelConfigDefault = `-- name: SetChannelConfigDefault :exec
UPDATE channel_configs
SET is_default = (id = $1)
WHERE workspace_id = $2 AND channel = $3 AND deleted_at IS NULL
`

type SetChannelConfigDefaultParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Channel     string      `db:"channel" json:"channel"`
}

func (q *Queries) SetChannelConfigDefault(ctx context.Context, arg SetChannelConfigDefaultParams) error {
	_, err := q.db.Exec(ctx, setChannelConfigDefault, arg.ID, arg.WorkspaceID, arg.Channel)
	return err
}

const softDeleteChannelConfig = `-- name: SoftDeleteChannelConfig :exec
UPDATE channel_configs 
SET 
    deleted_at = NOW(),
    is_active = false,
    is_default = false 
WHERE id = $1 AND workspace_id = $2
`

type SoftDeleteChannelConfigParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) SoftDeleteChannelConfig(ctx context.Context, arg SoftDeleteChannelConfigParams) error {
	_, err := q.db.Exec(ctx, softDeleteChannelConfig, arg.ID, arg.WorkspaceID)
	return err
}

const updateChannelConfig = `-- name: UpdateChannelConfig :one
UPDATE channel_configs
SET
    display_name = COALESCE($3, display_name),
    credentials  = COALESCE($4, credentials),
    is_active    = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at, deleted_at
`

type UpdateChannelConfigParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	DisplayName pgtype.Text `db:"display_name" json:"display_name"`
	Credentials pgtype.Text `db:"credentials" json:"credentials"`
	IsActive    pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateChannelConfig(ctx context.Context, arg UpdateChannelConfigParams) (ChannelConfig, error) {
	row := q.db.QueryRow(ctx, updateChannelConfig,
		arg.ID,
		arg.WorkspaceID,
		arg.DisplayName,
		arg.Credentials,
		arg.IsActive,
	)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Provider,
		&i.DisplayName,
		&i.Credentials,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
