// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelConfigByID = `-- name: GetChannelConfigByID :one
SELECT id, workspace_id, channel, provider, display_name, credentials, is_active, is_default, created_at, updated_at FROM channel_configs
WHERE id = $1
AND workspace_id = $2
AND is_active = true
`

type GetChannelConfigByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetChannelConfigByID(ctx context.Context, arg GetChannelConfigByIDParams) (ChannelConfig, error) {
	row := q.db.QueryRow(ctx, getChannelConfigByID, arg.ID, arg.WorkspaceID)
	var i ChannelConfig
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Channel,
		&i.Provider,
		&i.DisplayName,
		&i.Credentials,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
