// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: layout.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLayoutByID = `-- name: GetLayoutByID :one
SELECT id, workspace_id, name, is_default, html, created_at, updated_at FROM layouts
WHERE id = $1
AND workspace_id = $2
AND is_default=true
`

type GetLayoutByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetLayoutByID(ctx context.Context, arg GetLayoutByIDParams) (Layout, error) {
	row := q.db.QueryRow(ctx, getLayoutByID, arg.ID, arg.WorkspaceID)
	var i Layout
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.IsDefault,
		&i.Html,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
