// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationLogByID = `-- name: GetNotificationLogByID :one
SELECT id, workspace_id, environment_id, template_id, external_user_id, event_type, channel, status, rendered_content, idempotency_key, attempt_count, is_test, queued_at, recipient, sent_at, created_at FROM notification_logs
WHERE id = $1
`

func (q *Queries) GetNotificationLogByID(ctx context.Context, id pgtype.UUID) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getNotificationLogByID, id)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.TemplateID,
		&i.ExternalUserID,
		&i.EventType,
		&i.Channel,
		&i.Status,
		&i.RenderedContent,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.IsTest,
		&i.QueuedAt,
		&i.Recipient,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationLogByIdempotencyKey = `-- name: GetNotificationLogByIdempotencyKey :one
SELECT id, workspace_id, environment_id, template_id, external_user_id, event_type, channel, status, rendered_content, idempotency_key, attempt_count, is_test, queued_at, recipient, sent_at, created_at FROM notification_logs
WHERE idempotency_key = $1
`

func (q *Queries) GetNotificationLogByIdempotencyKey(ctx context.Context, idempotencyKey string) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, getNotificationLogByIdempotencyKey, idempotencyKey)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.TemplateID,
		&i.ExternalUserID,
		&i.EventType,
		&i.Channel,
		&i.Status,
		&i.RenderedContent,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.IsTest,
		&i.QueuedAt,
		&i.Recipient,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotificationLog = `-- name: InsertNotificationLog :one
INSERT INTO notification_logs (
    workspace_id,
    environment_id,
    template_id,
    external_user_id,
    event_type,
    channel,
    recipient,
    idempotency_key,
    is_test
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, workspace_id, environment_id, template_id, external_user_id, event_type, channel, status, rendered_content, idempotency_key, attempt_count, is_test, queued_at, recipient, sent_at, created_at
`

type InsertNotificationLogParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID  pgtype.UUID `db:"environment_id" json:"environment_id"`
	TemplateID     pgtype.UUID `db:"template_id" json:"template_id"`
	ExternalUserID string      `db:"external_user_id" json:"external_user_id"`
	EventType      string      `db:"event_type" json:"event_type"`
	Channel        string      `db:"channel" json:"channel"`
	Recipient      string      `db:"recipient" json:"recipient"`
	IdempotencyKey string      `db:"idempotency_key" json:"idempotency_key"`
	IsTest         bool        `db:"is_test" json:"is_test"`
}

func (q *Queries) InsertNotificationLog(ctx context.Context, arg InsertNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, insertNotificationLog,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.TemplateID,
		arg.ExternalUserID,
		arg.EventType,
		arg.Channel,
		arg.Recipient,
		arg.IdempotencyKey,
		arg.IsTest,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.TemplateID,
		&i.ExternalUserID,
		&i.EventType,
		&i.Channel,
		&i.Status,
		&i.RenderedContent,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.IsTest,
		&i.QueuedAt,
		&i.Recipient,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateNotificationLogStatus = `-- name: UpdateNotificationLogStatus :one
UPDATE notification_logs
SET
    status           = $2,
    rendered_content = $3,
    attempt_count    = $4,
    sent_at          = $5
WHERE id = $1
RETURNING id, workspace_id, environment_id, template_id, external_user_id, event_type, channel, status, rendered_content, idempotency_key, attempt_count, is_test, queued_at, recipient, sent_at, created_at
`

type UpdateNotificationLogStatusParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Status          string             `db:"status" json:"status"`
	RenderedContent []byte             `db:"rendered_content" json:"rendered_content"`
	AttemptCount    int32              `db:"attempt_count" json:"attempt_count"`
	SentAt          pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
}

func (q *Queries) UpdateNotificationLogStatus(ctx context.Context, arg UpdateNotificationLogStatusParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, updateNotificationLogStatus,
		arg.ID,
		arg.Status,
		arg.RenderedContent,
		arg.AttemptCount,
		arg.SentAt,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.TemplateID,
		&i.ExternalUserID,
		&i.EventType,
		&i.Channel,
		&i.Status,
		&i.RenderedContent,
		&i.IdempotencyKey,
		&i.AttemptCount,
		&i.IsTest,
		&i.QueuedAt,
		&i.Recipient,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}
