// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_attempts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttemptsByNotificationLogID = `-- name: GetAttemptsByNotificationLogID :many
SELECT id, notification_log_id, attempt_count, provider, channel_config_id, status, error_message, error_code, provider_message_id, duration_ms, attempted_at FROM notification_attempts
WHERE notification_log_id = $1
ORDER BY attempt_count ASC
`

func (q *Queries) GetAttemptsByNotificationLogID(ctx context.Context, notificationLogID pgtype.UUID) ([]NotificationAttempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsByNotificationLogID, notificationLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationAttempt
	for rows.Next() {
		var i NotificationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.NotificationLogID,
			&i.AttemptCount,
			&i.Provider,
			&i.ChannelConfigID,
			&i.Status,
			&i.ErrorMessage,
			&i.ErrorCode,
			&i.ProviderMessageID,
			&i.DurationMs,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotificationAttempt = `-- name: InsertNotificationAttempt :one
INSERT INTO notification_attempts (
    notification_log_id,
    attempt_count,
    status,
    error_message,
    provider,
    attempted_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
RETURNING id, notification_log_id, attempt_count, provider, channel_config_id, status, error_message, error_code, provider_message_id, duration_ms, attempted_at
`

type InsertNotificationAttemptParams struct {
	NotificationLogID pgtype.UUID `db:"notification_log_id" json:"notification_log_id"`
	AttemptCount      int32       `db:"attempt_count" json:"attempt_count"`
	Status            string      `db:"status" json:"status"`
	ErrorMessage      pgtype.Text `db:"error_message" json:"error_message"`
	Provider          string      `db:"provider" json:"provider"`
}

func (q *Queries) InsertNotificationAttempt(ctx context.Context, arg InsertNotificationAttemptParams) (NotificationAttempt, error) {
	row := q.db.QueryRow(ctx, insertNotificationAttempt,
		arg.NotificationLogID,
		arg.AttemptCount,
		arg.Status,
		arg.ErrorMessage,
		arg.Provider,
	)
	var i NotificationAttempt
	err := row.Scan(
		&i.ID,
		&i.NotificationLogID,
		&i.AttemptCount,
		&i.Provider,
		&i.ChannelConfigID,
		&i.Status,
		&i.ErrorMessage,
		&i.ErrorCode,
		&i.ProviderMessageID,
		&i.DurationMs,
		&i.AttemptedAt,
	)
	return i, err
}
