// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllPlans = `-- name: GetAllPlans :many
SELECT id, name, notif_limit_month, members_limit, api_keys_limit, log_retention_days, original_price_cents, price_cents, is_active, created_at, updated_at FROM plans
WHERE is_active = true
ORDER BY price_cents ASC
`

func (q *Queries) GetAllPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, getAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NotifLimitMonth,
			&i.MembersLimit,
			&i.ApiKeysLimit,
			&i.LogRetentionDays,
			&i.OriginalPriceCents,
			&i.PriceCents,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanByID = `-- name: GetPlanByID :one

SELECT id, name, notif_limit_month, members_limit, api_keys_limit, log_retention_days, original_price_cents, price_cents, is_active, created_at, updated_at FROM plans
WHERE id = $1
LIMIT 1
`

// sql/queries/plans.sql
func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NotifLimitMonth,
		&i.MembersLimit,
		&i.ApiKeysLimit,
		&i.LogRetentionDays,
		&i.OriginalPriceCents,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
