// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkspaceLayouts = `-- name: CountWorkspaceLayouts :one
select count(*)
from layouts
where workspace_id = $1
`

func (q *Queries) CountWorkspaceLayouts(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceLayouts, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceTemplates = `-- name: CountWorkspaceTemplates :one
SELECT COUNT(*)
FROM templates
WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceTemplates(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceTemplates, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllPlans = `-- name: GetAllPlans :many
SELECT id, name, members_limit, api_keys_limit, log_retention_days, original_price_cents, price_cents, is_active, created_at, updated_at, max_layouts, max_templates, email_limit_month, sms_limit_month, push_limit_month, slack_limit_month, whatsapp_limit_month, webhook_limit_month, in_app_limit_month, external_price_id
FROM plans
WHERE is_active = true
ORDER BY price_cents ASC
`

func (q *Queries) GetAllPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, getAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MembersLimit,
			&i.ApiKeysLimit,
			&i.LogRetentionDays,
			&i.OriginalPriceCents,
			&i.PriceCents,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxLayouts,
			&i.MaxTemplates,
			&i.EmailLimitMonth,
			&i.SmsLimitMonth,
			&i.PushLimitMonth,
			&i.SlackLimitMonth,
			&i.WhatsappLimitMonth,
			&i.WebhookLimitMonth,
			&i.InAppLimitMonth,
			&i.ExternalPriceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, members_limit, api_keys_limit, log_retention_days, original_price_cents, price_cents, is_active, created_at, updated_at, max_layouts, max_templates, email_limit_month, sms_limit_month, push_limit_month, slack_limit_month, whatsapp_limit_month, webhook_limit_month, in_app_limit_month, external_price_id
FROM plans
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MembersLimit,
		&i.ApiKeysLimit,
		&i.LogRetentionDays,
		&i.OriginalPriceCents,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxLayouts,
		&i.MaxTemplates,
		&i.EmailLimitMonth,
		&i.SmsLimitMonth,
		&i.PushLimitMonth,
		&i.SlackLimitMonth,
		&i.WhatsappLimitMonth,
		&i.WebhookLimitMonth,
		&i.InAppLimitMonth,
		&i.ExternalPriceID,
	)
	return i, err
}

const getPlanByWorkspace = `-- name: GetPlanByWorkspace :one
SELECT p.id, p.name, p.members_limit, p.api_keys_limit, p.log_retention_days, p.original_price_cents, p.price_cents, p.is_active, p.created_at, p.updated_at, p.max_layouts, p.max_templates, p.email_limit_month, p.sms_limit_month, p.push_limit_month, p.slack_limit_month, p.whatsapp_limit_month, p.webhook_limit_month, p.in_app_limit_month, p.external_price_id
from plans as p
    join workspaces as w on w.plan_id = p.id
where w.id = $1
    and is_active = true
`

func (q *Queries) GetPlanByWorkspace(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByWorkspace, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MembersLimit,
		&i.ApiKeysLimit,
		&i.LogRetentionDays,
		&i.OriginalPriceCents,
		&i.PriceCents,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxLayouts,
		&i.MaxTemplates,
		&i.EmailLimitMonth,
		&i.SmsLimitMonth,
		&i.PushLimitMonth,
		&i.SlackLimitMonth,
		&i.WhatsappLimitMonth,
		&i.WebhookLimitMonth,
		&i.InAppLimitMonth,
		&i.ExternalPriceID,
	)
	return i, err
}
