// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTemplateByEventAndChannel = `-- name: GetTemplateByEventAndChannel :one
SELECT id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at FROM templates 
WHERE event_type = $1 
  AND workspace_id = $2
  AND environment_id = $3
  AND status = 'live'
LIMIT 1
`

type GetTemplateByEventAndChannelParams struct {
	EventType     string      `db:"event_type" json:"event_type"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetTemplateByEventAndChannel(ctx context.Context, arg GetTemplateByEventAndChannelParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByEventAndChannel, arg.EventType, arg.WorkspaceID, arg.EnvironmentID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.LayoutID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByEventType = `-- name: GetTemplateByEventType :one
SELECT id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at FROM templates 
WHERE event_type = $1 
  AND workspace_id = $2 
  AND environment_id = $3
LIMIT 1
`

type GetTemplateByEventTypeParams struct {
	EventType     string      `db:"event_type" json:"event_type"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetTemplateByEventType(ctx context.Context, arg GetTemplateByEventTypeParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByEventType, arg.EventType, arg.WorkspaceID, arg.EnvironmentID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.LayoutID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
