// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_channel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplateChannel = `-- name: CreateTemplateChannel :one
INSERT INTO template_channels (
    template_id,
    channel_config_id,
    channel,
    content,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at
`

type CreateTemplateChannelParams struct {
	TemplateID      pgtype.UUID `db:"template_id" json:"template_id"`
	ChannelConfigID pgtype.UUID `db:"channel_config_id" json:"channel_config_id"`
	Channel         string      `db:"channel" json:"channel"`
	Content         []byte      `db:"content" json:"content"`
	IsActive        pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateTemplateChannel(ctx context.Context, arg CreateTemplateChannelParams) (TemplateChannel, error) {
	row := q.db.QueryRow(ctx, createTemplateChannel,
		arg.TemplateID,
		arg.ChannelConfigID,
		arg.Channel,
		arg.Content,
		arg.IsActive,
	)
	var i TemplateChannel
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ChannelConfigID,
		&i.Channel,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplateChannel = `-- name: DeleteTemplateChannel :execresult
DELETE FROM template_channels
WHERE id = $1 AND template_id = $2
`

type DeleteTemplateChannelParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	TemplateID pgtype.UUID `db:"template_id" json:"template_id"`
}

func (q *Queries) DeleteTemplateChannel(ctx context.Context, arg DeleteTemplateChannelParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteTemplateChannel, arg.ID, arg.TemplateID)
}

const getActiveChannelsByTemplateID = `-- name: GetActiveChannelsByTemplateID :many
SELECT id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at FROM template_channels
WHERE template_id = $1
AND is_active = true
`

func (q *Queries) GetActiveChannelsByTemplateID(ctx context.Context, templateID pgtype.UUID) ([]TemplateChannel, error) {
	rows, err := q.db.Query(ctx, getActiveChannelsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateChannel
	for rows.Next() {
		var i TemplateChannel
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ChannelConfigID,
			&i.Channel,
			&i.Content,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateChannelByID = `-- name: GetTemplateChannelByID :one
SELECT id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at FROM template_channels
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTemplateChannelByID(ctx context.Context, id pgtype.UUID) (TemplateChannel, error) {
	row := q.db.QueryRow(ctx, getTemplateChannelByID, id)
	var i TemplateChannel
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ChannelConfigID,
		&i.Channel,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateChannelByTemplateAndChannel = `-- name: GetTemplateChannelByTemplateAndChannel :one
SELECT id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at FROM template_channels
WHERE template_id = $1
AND channel = $2
AND is_active = true
`

type GetTemplateChannelByTemplateAndChannelParams struct {
	TemplateID pgtype.UUID `db:"template_id" json:"template_id"`
	Channel    string      `db:"channel" json:"channel"`
}

func (q *Queries) GetTemplateChannelByTemplateAndChannel(ctx context.Context, arg GetTemplateChannelByTemplateAndChannelParams) (TemplateChannel, error) {
	row := q.db.QueryRow(ctx, getTemplateChannelByTemplateAndChannel, arg.TemplateID, arg.Channel)
	var i TemplateChannel
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ChannelConfigID,
		&i.Channel,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveChannels = `-- name: HasActiveChannels :one
SELECT EXISTS (
    SELECT 1 FROM template_channels 
    WHERE template_id = $1 AND is_active = true
)
`

func (q *Queries) HasActiveChannels(ctx context.Context, templateID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveChannels, templateID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTemplateChannels = `-- name: ListTemplateChannels :many
SELECT id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at FROM template_channels
WHERE template_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTemplateChannels(ctx context.Context, templateID pgtype.UUID) ([]TemplateChannel, error) {
	rows, err := q.db.Query(ctx, listTemplateChannels, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateChannel
	for rows.Next() {
		var i TemplateChannel
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ChannelConfigID,
			&i.Channel,
			&i.Content,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplateChannel = `-- name: UpdateTemplateChannel :one
UPDATE template_channels
SET
    channel_config_id = $2,
    content = $3,
    is_active = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at
`

type UpdateTemplateChannelParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ChannelConfigID pgtype.UUID `db:"channel_config_id" json:"channel_config_id"`
	Content         []byte      `db:"content" json:"content"`
	IsActive        pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateTemplateChannel(ctx context.Context, arg UpdateTemplateChannelParams) (TemplateChannel, error) {
	row := q.db.QueryRow(ctx, updateTemplateChannel,
		arg.ID,
		arg.ChannelConfigID,
		arg.Content,
		arg.IsActive,
	)
	var i TemplateChannel
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ChannelConfigID,
		&i.Channel,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
