// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM templates
WHERE workspace_id = $1
`

func (q *Queries) CountTemplates(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplates, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
    workspace_id,
    environment_id,
    layout_id,
    created_by,
    name,
    description,
    event_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at
`

type CreateTemplateParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
	LayoutID      pgtype.UUID `db:"layout_id" json:"layout_id"`
	CreatedBy     pgtype.UUID `db:"created_by" json:"created_by"`
	Name          string      `db:"name" json:"name"`
	Description   pgtype.Text `db:"description" json:"description"`
	EventType     string      `db:"event_type" json:"event_type"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.LayoutID,
		arg.CreatedBy,
		arg.Name,
		arg.Description,
		arg.EventType,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.LayoutID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates
WHERE id = $1 AND workspace_id = $2
`

type DeleteTemplateParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.WorkspaceID)
	return err
}

const getTemplateByEventAndChannel = `-- name: GetTemplateByEventAndChannel :one
SELECT id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at FROM templates 
WHERE event_type = $1 
  AND workspace_id = $2
  AND environment_id = $3
  AND status = 'live'
LIMIT 1
`

type GetTemplateByEventAndChannelParams struct {
	EventType     string      `db:"event_type" json:"event_type"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetTemplateByEventAndChannel(ctx context.Context, arg GetTemplateByEventAndChannelParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByEventAndChannel, arg.EventType, arg.WorkspaceID, arg.EnvironmentID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.LayoutID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByEventType = `-- name: GetTemplateByEventType :one
SELECT id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at FROM templates 
WHERE event_type = $1 
  AND workspace_id = $2 
  AND environment_id = $3
LIMIT 1
`

type GetTemplateByEventTypeParams struct {
	EventType     string      `db:"event_type" json:"event_type"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetTemplateByEventType(ctx context.Context, arg GetTemplateByEventTypeParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByEventType, arg.EventType, arg.WorkspaceID, arg.EnvironmentID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.LayoutID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at FROM templates
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetTemplateByIDParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID, arg.WorkspaceID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.LayoutID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at FROM templates
WHERE workspace_id = $1 AND environment_id = $2
ORDER BY created_at DESC
`

type ListTemplatesParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.WorkspaceID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.LayoutID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.EventType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET
    name = $3,
    description = $4,
    status = $5,
    layout_id = $6,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, environment_id, layout_id, created_by, name, description, event_type, status, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	Status      string      `db:"status" json:"status"`
	LayoutID    pgtype.UUID `db:"layout_id" json:"layout_id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.LayoutID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.LayoutID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
