// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template_channel.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveChannelsByTemplateID = `-- name: GetActiveChannelsByTemplateID :many
SELECT id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at FROM template_channels
WHERE template_id = $1
AND is_active = true
`

func (q *Queries) GetActiveChannelsByTemplateID(ctx context.Context, templateID pgtype.UUID) ([]TemplateChannel, error) {
	rows, err := q.db.Query(ctx, getActiveChannelsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateChannel
	for rows.Next() {
		var i TemplateChannel
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ChannelConfigID,
			&i.Channel,
			&i.Content,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateChannelByTemplateAndChannel = `-- name: GetTemplateChannelByTemplateAndChannel :one
SELECT id, template_id, channel_config_id, channel, content, is_active, created_at, updated_at FROM template_channels
WHERE template_id = $1
AND channel = $2
AND is_active = true
`

type GetTemplateChannelByTemplateAndChannelParams struct {
	TemplateID pgtype.UUID `db:"template_id" json:"template_id"`
	Channel    string      `db:"channel" json:"channel"`
}

func (q *Queries) GetTemplateChannelByTemplateAndChannel(ctx context.Context, arg GetTemplateChannelByTemplateAndChannelParams) (TemplateChannel, error) {
	row := q.db.QueryRow(ctx, getTemplateChannelByTemplateAndChannel, arg.TemplateID, arg.Channel)
	var i TemplateChannel
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ChannelConfigID,
		&i.Channel,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
