// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_info.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContactByExternalUserAndChannel = `-- name: GetContactByExternalUserAndChannel :one
SELECT id, workspace_id, environment_id, external_user_id, channel, contact_value, metadata, verified, created_at, updated_at FROM user_info
WHERE workspace_id    = $1
  AND environment_id  = $2
  AND external_user_id = $3
  AND channel         = $4
`

type GetContactByExternalUserAndChannelParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID  pgtype.UUID `db:"environment_id" json:"environment_id"`
	ExternalUserID string      `db:"external_user_id" json:"external_user_id"`
	Channel        string      `db:"channel" json:"channel"`
}

func (q *Queries) GetContactByExternalUserAndChannel(ctx context.Context, arg GetContactByExternalUserAndChannelParams) (UserInfo, error) {
	row := q.db.QueryRow(ctx, getContactByExternalUserAndChannel,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.ExternalUserID,
		arg.Channel,
	)
	var i UserInfo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.ExternalUserID,
		&i.Channel,
		&i.ContactValue,
		&i.Metadata,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserContactInfo = `-- name: UpsertUserContactInfo :one
INSERT INTO user_info (
    workspace_id,
    environment_id,
    external_user_id,
    channel,
    contact_value,
    verified,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (workspace_id, environment_id, external_user_id, channel)
DO UPDATE SET
    contact_value = EXCLUDED.contact_value,
    metadata      = EXCLUDED.metadata
RETURNING id, workspace_id, environment_id, external_user_id, channel, contact_value, metadata, verified, created_at, updated_at
`

type UpsertUserContactInfoParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID  pgtype.UUID `db:"environment_id" json:"environment_id"`
	ExternalUserID string      `db:"external_user_id" json:"external_user_id"`
	Channel        string      `db:"channel" json:"channel"`
	ContactValue   string      `db:"contact_value" json:"contact_value"`
	Verified       pgtype.Bool `db:"verified" json:"verified"`
	Metadata       []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertUserContactInfo(ctx context.Context, arg UpsertUserContactInfoParams) (UserInfo, error) {
	row := q.db.QueryRow(ctx, upsertUserContactInfo,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.ExternalUserID,
		arg.Channel,
		arg.ContactValue,
		arg.Verified,
		arg.Metadata,
	)
	var i UserInfo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.ExternalUserID,
		&i.Channel,
		&i.ContactValue,
		&i.Metadata,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
