// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_info.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubscribers = `-- name: CountSubscribers :one
SELECT count(*) FROM user_info
WHERE workspace_id = $1
  AND environment_id = $2
`

type CountSubscribersParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) CountSubscribers(ctx context.Context, arg CountSubscribersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscribers, arg.WorkspaceID, arg.EnvironmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserContactInfo = `-- name: DeleteUserContactInfo :exec
DELETE FROM user_info
WHERE id = $1
  AND workspace_id = $2
`

type DeleteUserContactInfoParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
}

func (q *Queries) DeleteUserContactInfo(ctx context.Context, arg DeleteUserContactInfoParams) error {
	_, err := q.db.Exec(ctx, deleteUserContactInfo, arg.ID, arg.WorkspaceID)
	return err
}

const getContactByExternalUserAndChannel = `-- name: GetContactByExternalUserAndChannel :one
SELECT id, workspace_id, environment_id, external_user_id, channel, contact_value, metadata, verified, created_at, updated_at FROM user_info
WHERE workspace_id    = $1
  AND environment_id  = $2
  AND external_user_id = $3
  AND channel         = $4
`

type GetContactByExternalUserAndChannelParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID  pgtype.UUID `db:"environment_id" json:"environment_id"`
	ExternalUserID string      `db:"external_user_id" json:"external_user_id"`
	Channel        string      `db:"channel" json:"channel"`
}

func (q *Queries) GetContactByExternalUserAndChannel(ctx context.Context, arg GetContactByExternalUserAndChannelParams) (UserInfo, error) {
	row := q.db.QueryRow(ctx, getContactByExternalUserAndChannel,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.ExternalUserID,
		arg.Channel,
	)
	var i UserInfo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.ExternalUserID,
		&i.Channel,
		&i.ContactValue,
		&i.Metadata,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT id, workspace_id, environment_id, external_user_id, channel, contact_value, metadata, verified, created_at, updated_at FROM user_info
WHERE workspace_id = $1
  AND environment_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListSubscribersParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
	Limit         int32       `db:"limit" json:"limit"`
	Offset        int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListSubscribers(ctx context.Context, arg ListSubscribersParams) ([]UserInfo, error) {
	rows, err := q.db.Query(ctx, listSubscribers,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInfo
	for rows.Next() {
		var i UserInfo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.ExternalUserID,
			&i.Channel,
			&i.ContactValue,
			&i.Metadata,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserContactInfo = `-- name: UpsertUserContactInfo :one
INSERT INTO user_info (
    workspace_id,
    environment_id,
    external_user_id,
    channel,
    contact_value,
    verified,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (workspace_id, environment_id, external_user_id, channel)
DO UPDATE SET
    contact_value = EXCLUDED.contact_value,
    metadata      = EXCLUDED.metadata,
    verified      = EXCLUDED.verified
RETURNING id, workspace_id, environment_id, external_user_id, channel, contact_value, metadata, verified, created_at, updated_at
`

type UpsertUserContactInfoParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID  pgtype.UUID `db:"environment_id" json:"environment_id"`
	ExternalUserID string      `db:"external_user_id" json:"external_user_id"`
	Channel        string      `db:"channel" json:"channel"`
	ContactValue   string      `db:"contact_value" json:"contact_value"`
	Verified       pgtype.Bool `db:"verified" json:"verified"`
	Metadata       []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertUserContactInfo(ctx context.Context, arg UpsertUserContactInfoParams) (UserInfo, error) {
	row := q.db.QueryRow(ctx, upsertUserContactInfo,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.ExternalUserID,
		arg.Channel,
		arg.ContactValue,
		arg.Verified,
		arg.Metadata,
	)
	var i UserInfo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.ExternalUserID,
		&i.Channel,
		&i.ContactValue,
		&i.Metadata,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
