// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContactWithPreference = `-- name: GetContactWithPreference :one
SELECT u.id, u.workspace_id, u.environment_id, u.external_user_id, u.channel, u.contact_value, u.metadata, u.verified, u.created_at, u.updated_at,p.id, p.workspace_id, p.environment_id, p.subscriber_id, p.channel, p.event_type, p.is_enabled, p.created_at, p.updated_at from user_info as u LEFT JOIN
user_preferences as p on 
u.id=p.subscriber_id AND
p.event_type=$4 and p.channel=$5
WHERE u.external_user_id=$1
AND u.workspace_id=$2 
AND u.environment_id=$3
AND u.channel=$5
`

type GetContactWithPreferenceParams struct {
	ExternalUserID string      `db:"external_user_id" json:"external_user_id"`
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID  pgtype.UUID `db:"environment_id" json:"environment_id"`
	EventType      pgtype.Text `db:"event_type" json:"event_type"`
	Channel        string      `db:"channel" json:"channel"`
}

type GetContactWithPreferenceRow struct {
	UserInfo       UserInfo       `db:"user_info" json:"user_info"`
	UserPreference UserPreference `db:"user_preference" json:"user_preference"`
}

func (q *Queries) GetContactWithPreference(ctx context.Context, arg GetContactWithPreferenceParams) (GetContactWithPreferenceRow, error) {
	row := q.db.QueryRow(ctx, getContactWithPreference,
		arg.ExternalUserID,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.EventType,
		arg.Channel,
	)
	var i GetContactWithPreferenceRow
	err := row.Scan(
		&i.UserInfo.ID,
		&i.UserInfo.WorkspaceID,
		&i.UserInfo.EnvironmentID,
		&i.UserInfo.ExternalUserID,
		&i.UserInfo.Channel,
		&i.UserInfo.ContactValue,
		&i.UserInfo.Metadata,
		&i.UserInfo.Verified,
		&i.UserInfo.CreatedAt,
		&i.UserInfo.UpdatedAt,
		&i.UserPreference.ID,
		&i.UserPreference.WorkspaceID,
		&i.UserPreference.EnvironmentID,
		&i.UserPreference.SubscriberID,
		&i.UserPreference.Channel,
		&i.UserPreference.EventType,
		&i.UserPreference.IsEnabled,
		&i.UserPreference.CreatedAt,
		&i.UserPreference.UpdatedAt,
	)
	return i, err
}

const getPreferencesBySubscriberAndChannel = `-- name: GetPreferencesBySubscriberAndChannel :many
SELECT id, workspace_id, environment_id, subscriber_id, channel, event_type, is_enabled, created_at, updated_at FROM user_preferences
WHERE subscriber_id = $1
  AND channel       = $2
  AND (event_type IS NULL OR event_type = $3)
`

type GetPreferencesBySubscriberAndChannelParams struct {
	SubscriberID pgtype.UUID `db:"subscriber_id" json:"subscriber_id"`
	Channel      string      `db:"channel" json:"channel"`
	EventType    pgtype.Text `db:"event_type" json:"event_type"`
}

func (q *Queries) GetPreferencesBySubscriberAndChannel(ctx context.Context, arg GetPreferencesBySubscriberAndChannelParams) ([]UserPreference, error) {
	rows, err := q.db.Query(ctx, getPreferencesBySubscriberAndChannel, arg.SubscriberID, arg.Channel, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPreference
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.SubscriberID,
			&i.Channel,
			&i.EventType,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPreferencesBySubscriber = `-- name: ListUserPreferencesBySubscriber :many
SELECT up.id, up.workspace_id, up.environment_id, up.subscriber_id, up.channel, up.event_type, up.is_enabled, up.created_at, up.updated_at FROM user_preferences up
JOIN user_info ui ON up.subscriber_id = ui.id
WHERE ui.workspace_id = $1 
  AND ui.environment_id = $2 
  AND ui.external_user_id = $3
`

type ListUserPreferencesBySubscriberParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID  pgtype.UUID `db:"environment_id" json:"environment_id"`
	ExternalUserID string      `db:"external_user_id" json:"external_user_id"`
}

func (q *Queries) ListUserPreferencesBySubscriber(ctx context.Context, arg ListUserPreferencesBySubscriberParams) ([]UserPreference, error) {
	rows, err := q.db.Query(ctx, listUserPreferencesBySubscriber, arg.WorkspaceID, arg.EnvironmentID, arg.ExternalUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPreference
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.SubscriberID,
			&i.Channel,
			&i.EventType,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPreference = `-- name: UpsertUserPreference :one
INSERT INTO user_preferences (
    workspace_id,
    environment_id,
    subscriber_id,
    channel,
    event_type,
    is_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (subscriber_id, channel, event_type)
DO UPDATE SET
    is_enabled = EXCLUDED.is_enabled
RETURNING id, workspace_id, environment_id, subscriber_id, channel, event_type, is_enabled, created_at, updated_at
`

type UpsertUserPreferenceParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
	SubscriberID  pgtype.UUID `db:"subscriber_id" json:"subscriber_id"`
	Channel       string      `db:"channel" json:"channel"`
	EventType     pgtype.Text `db:"event_type" json:"event_type"`
	IsEnabled     bool        `db:"is_enabled" json:"is_enabled"`
}

func (q *Queries) UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreference,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.SubscriberID,
		arg.Channel,
		arg.EventType,
		arg.IsEnabled,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.SubscriberID,
		&i.Channel,
		&i.EventType,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
