// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwners = `-- name: CountOwners :one
SELECT count(*) 
FROM workspace_members 
WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :one
INSERT INTO workspace_members (id, workspace_id, user_id, role, joined_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW())
RETURNING id, workspace_id, user_id, role, invited_by, joined_at, created_at
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Role        string      `db:"role" json:"role"`
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, createWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1
AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM workspace_members
WHERE workspace_id = $1
AND user_id = $2
LIMIT 1
`

type GetMemberRoleParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getWorkspaceMemberByID = `-- name: GetWorkspaceMemberByID :one

select id, workspace_id, user_id, role, invited_by, joined_at, created_at from workspace_members where id = $1 limit 1
`

func (q *Queries) GetWorkspaceMemberByID(ctx context.Context, id pgtype.UUID) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberByID, id)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMemberByUserID = `-- name: GetWorkspaceMemberByUserID :one

select id, workspace_id, user_id, role, invited_by, joined_at, created_at from workspace_members where user_id = $1 limit 1
`

func (q *Queries) GetWorkspaceMemberByUserID(ctx context.Context, userID pgtype.UUID) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberByUserID, userID)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMembers = `-- name: GetWorkspaceMembers :many
SELECT id, workspace_id, user_id, role, invited_by, joined_at, created_at FROM workspace_members
WHERE workspace_id = $1
`

func (q *Queries) GetWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceMember
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceMembersWithDetails = `-- name: GetWorkspaceMembersWithDetails :many
SELECT 
    m.workspace_id,
    m.user_id, 
    u.full_name as name, 
    u.email, 
    u.avatar_url, 
    m.role, 
    m.joined_at
FROM workspace_members m
JOIN users u ON m.user_id = u.id
WHERE m.workspace_id = $1
`

type GetWorkspaceMembersWithDetailsRow struct {
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Name        string             `db:"name" json:"name"`
	Email       string             `db:"email" json:"email"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Role        string             `db:"role" json:"role"`
	JoinedAt    pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

func (q *Queries) GetWorkspaceMembersWithDetails(ctx context.Context, workspaceID pgtype.UUID) ([]GetWorkspaceMembersWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceMembersWithDetails, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceMembersWithDetailsRow
	for rows.Next() {
		var i GetWorkspaceMembersWithDetailsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceOwnerEmails = `-- name: GetWorkspaceOwnerEmails :many
SELECT u.email FROM workspace_members m
JOIN users u ON m.user_id = u.id
WHERE m.workspace_id = $1 AND m.role = 'owner'
`

func (q *Queries) GetWorkspaceOwnerEmails(ctx context.Context, workspaceID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getWorkspaceOwnerEmails, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE workspace_members
SET role = $3
WHERE workspace_id = $1
AND user_id = $2
RETURNING id, workspace_id, user_id, role, invited_by, joined_at, created_at
`

type UpdateMemberRoleParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Role        string      `db:"role" json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}
