// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one

INSERT INTO workspaces (id, name, slug,plan_id) VALUES
(
    gen_random_uuid(),
    $1,
    $2,
    (SELECT id FROM plans WHERE name = 'Free' LIMIT 1)
) RETURNING id, name, slug, plan_id, notif_count_month, billing_cycle_start, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name string `db:"name" json:"name"`
	Slug string `db:"slug" json:"slug"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.NotifCountMonth,
		&i.BillingCycleStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const findWorkspaceByID = `-- name: FindWorkspaceByID :one
SELECT id, name, slug, plan_id, notif_count_month, billing_cycle_start, created_at, updated_at from workspaces where id = $1 LIMIT 1
`

func (q *Queries) FindWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, findWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.NotifCountMonth,
		&i.BillingCycleStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, plan_id, notif_count_month, billing_cycle_start, created_at, updated_at FROM workspaces
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.NotifCountMonth,
		&i.BillingCycleStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceWithEnvironmentsBySlug = `-- name: GetWorkspaceWithEnvironmentsBySlug :many
SELECT 
    w.id, w.name, w.slug, w.plan_id, w.notif_count_month, w.billing_cycle_start, w.created_at, w.updated_at, 
    e.id, e.workspace_id, e.name, e.created_at,
    p.name as plan_name
FROM workspaces w
JOIN plans p ON p.id = w.plan_id
LEFT JOIN environments e ON w.id = e.workspace_id
WHERE w.slug = $1
`

type GetWorkspaceWithEnvironmentsBySlugRow struct {
	Workspace   Workspace   `db:"workspace" json:"workspace"`
	Environment Environment `db:"environment" json:"environment"`
	PlanName    string      `db:"plan_name" json:"plan_name"`
}

func (q *Queries) GetWorkspaceWithEnvironmentsBySlug(ctx context.Context, slug string) ([]GetWorkspaceWithEnvironmentsBySlugRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaceWithEnvironmentsBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspaceWithEnvironmentsBySlugRow
	for rows.Next() {
		var i GetWorkspaceWithEnvironmentsBySlugRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.Name,
			&i.Workspace.Slug,
			&i.Workspace.PlanID,
			&i.Workspace.NotifCountMonth,
			&i.Workspace.BillingCycleStart,
			&i.Workspace.CreatedAt,
			&i.Workspace.UpdatedAt,
			&i.Environment.ID,
			&i.Environment.WorkspaceID,
			&i.Environment.Name,
			&i.Environment.CreatedAt,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceWithPlan = `-- name: GetWorkspaceWithPlan :one
SELECT 
    w.id, 
    w.name, 
    w.slug, 
    p.name as plan_name,
    w.created_at,
    w.plan_id, 
    p.api_keys_limit, 
    p.max_templates, 
    p.max_layouts
FROM workspaces w
JOIN plans p ON p.id = w.plan_id
WHERE w.id = $1
`

type GetWorkspaceWithPlanRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Slug         string             `db:"slug" json:"slug"`
	PlanName     string             `db:"plan_name" json:"plan_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PlanID       pgtype.UUID        `db:"plan_id" json:"plan_id"`
	ApiKeysLimit int32              `db:"api_keys_limit" json:"api_keys_limit"`
	MaxTemplates int32              `db:"max_templates" json:"max_templates"`
	MaxLayouts   int32              `db:"max_layouts" json:"max_layouts"`
}

func (q *Queries) GetWorkspaceWithPlan(ctx context.Context, id pgtype.UUID) (GetWorkspaceWithPlanRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceWithPlan, id)
	var i GetWorkspaceWithPlanRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanName,
		&i.CreatedAt,
		&i.PlanID,
		&i.ApiKeysLimit,
		&i.MaxTemplates,
		&i.MaxLayouts,
	)
	return i, err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :one
UPDATE workspaces
SET name       = $2,
    slug       = $3
WHERE id = $1
RETURNING id, name, slug, plan_id, notif_count_month, billing_cycle_start, created_at, updated_at
`

type UpdateWorkspaceNameParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Slug string      `db:"slug" json:"slug"`
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceName, arg.ID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.NotifCountMonth,
		&i.BillingCycleStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspacePlan = `-- name: UpdateWorkspacePlan :one

UPDATE workspaces
SET plan_id    = $2
WHERE id = $1
RETURNING id, name, slug, plan_id, notif_count_month, billing_cycle_start, created_at, updated_at
`

type UpdateWorkspacePlanParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	PlanID pgtype.UUID `db:"plan_id" json:"plan_id"`
}

func (q *Queries) UpdateWorkspacePlan(ctx context.Context, arg UpdateWorkspacePlanParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspacePlan, arg.ID, arg.PlanID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PlanID,
		&i.NotifCountMonth,
		&i.BillingCycleStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
