// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	billing "github.com/NIROOZbx/notification-engine/internal/billing"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CancelSubscription provides a mock function with given fields: ctx, workspaceID, subscriptionID
func (_m *Client) CancelSubscription(ctx context.Context, workspaceID string, subscriptionID string) error {
	ret := _m.Called(ctx, workspaceID, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for CancelSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, workspaceID, subscriptionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckLimit provides a mock function with given fields: ctx, workspaceID, environmentID, channel
func (_m *Client) CheckLimit(ctx context.Context, workspaceID string, environmentID string, channel string) (*billing.CheckLimitResponse, error) {
	ret := _m.Called(ctx, workspaceID, environmentID, channel)

	if len(ret) == 0 {
		panic("no return value specified for CheckLimit")
	}

	var r0 *billing.CheckLimitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*billing.CheckLimitResponse, error)); ok {
		return rf(ctx, workspaceID, environmentID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *billing.CheckLimitResponse); ok {
		r0 = rf(ctx, workspaceID, environmentID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CheckLimitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, environmentID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with no fields
func (_m *Client) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCheckoutSession provides a mock function with given fields: ctx, workspaceID, planID, customerEmail
func (_m *Client) CreateCheckoutSession(ctx context.Context, workspaceID string, planID string, customerEmail string) (string, error) {
	ret := _m.Called(ctx, workspaceID, planID, customerEmail)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, workspaceID, planID, customerEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, workspaceID, planID, customerEmail)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, planID, customerEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSubscription provides a mock function with given fields: ctx, workspaceID, planID, paymentProvider
func (_m *Client) CreateSubscription(ctx context.Context, workspaceID string, planID string, paymentProvider string) (string, error) {
	ret := _m.Called(ctx, workspaceID, planID, paymentProvider)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, workspaceID, planID, paymentProvider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, workspaceID, planID, paymentProvider)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, planID, paymentProvider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCheckoutSession provides a mock function with given fields: ctx, sessionID
func (_m *Client) GetCheckoutSession(ctx context.Context, sessionID string) (*billing.CheckoutSessionDetails, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutSession")
	}

	var r0 *billing.CheckoutSessionDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*billing.CheckoutSessionDetails, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.CheckoutSessionDetails); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CheckoutSessionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscription provides a mock function with given fields: ctx, workspaceID
func (_m *Client) GetSubscription(ctx context.Context, workspaceID string) (*billing.SubscriptionResponse, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 *billing.SubscriptionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*billing.SubscriptionResponse, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.SubscriptionResponse); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.SubscriptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsage provides a mock function with given fields: ctx, workspaceID, environmentID
func (_m *Client) GetUsage(ctx context.Context, workspaceID string, environmentID string) (*billing.UsageResponse, error) {
	ret := _m.Called(ctx, workspaceID, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsage")
	}

	var r0 *billing.UsageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*billing.UsageResponse, error)); ok {
		return rf(ctx, workspaceID, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *billing.UsageResponse); ok {
		r0 = rf(ctx, workspaceID, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.UsageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordUsage provides a mock function with given fields: ctx, input
func (_m *Client) RecordUsage(ctx context.Context, input billing.RecordUsageInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RecordUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, billing.RecordUsageInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
