// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

// GetActivityLogs provides a mock function with given fields: ctx, workspaceID, channel, status, page, pageSize
func (_m *AnalyticsService) GetActivityLogs(ctx context.Context, workspaceID string, channel *string, status *string, page int32, pageSize int32) (*domain.ActivityLogResponse, error) {
	ret := _m.Called(ctx, workspaceID, channel, status, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityLogs")
	}

	var r0 *domain.ActivityLogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) (*domain.ActivityLogResponse, error)); ok {
		return rf(ctx, workspaceID, channel, status, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string, int32, int32) *domain.ActivityLogResponse); ok {
		r0 = rf(ctx, workspaceID, channel, status, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActivityLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string, int32, int32) error); ok {
		r1 = rf(ctx, workspaceID, channel, status, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFullAnalytics provides a mock function with given fields: ctx, workspaceID, start, end, groupBy
func (_m *AnalyticsService) GetFullAnalytics(ctx context.Context, workspaceID string, start time.Time, end time.Time, groupBy string) (*domain.AnalyticsResponse, error) {
	ret := _m.Called(ctx, workspaceID, start, end, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetFullAnalytics")
	}

	var r0 *domain.AnalyticsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string) (*domain.AnalyticsResponse, error)); ok {
		return rf(ctx, workspaceID, start, end, groupBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, string) *domain.AnalyticsResponse); ok {
		r0 = rf(ctx, workspaceID, start, end, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AnalyticsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, workspaceID, start, end, groupBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
