// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/NIROOZbx/notification-engine/internal/dtos"
	mock "github.com/stretchr/testify/mock"

	services "github.com/NIROOZbx/notification-engine/internal/services"
)

// APIKeyService is an autogenerated mock type for the APIKeyService type
type APIKeyService struct {
	mock.Mock
}

// CreateAPIKey provides a mock function with given fields: ctx, params
func (_m *APIKeyService) CreateAPIKey(ctx context.Context, params services.CreateAPIKeyParams) (*dtos.CreateAPIKeyResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateAPIKey")
	}

	var r0 *dtos.CreateAPIKeyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateAPIKeyParams) (*dtos.CreateAPIKeyResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateAPIKeyParams) *dtos.CreateAPIKeyResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.CreateAPIKeyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.CreateAPIKeyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAPIKey provides a mock function with given fields: ctx, params
func (_m *APIKeyService) DeleteAPIKey(ctx context.Context, params services.DeleteKeyParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAPIKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.DeleteKeyParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListAPIKeys provides a mock function with given fields: ctx, params
func (_m *APIKeyService) ListAPIKeys(ctx context.Context, params services.ListApiKeyParams) ([]dtos.APIKeyInfo, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAPIKeys")
	}

	var r0 []dtos.APIKeyInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListApiKeyParams) ([]dtos.APIKeyInfo, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ListApiKeyParams) []dtos.APIKeyInfo); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.APIKeyInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ListApiKeyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeAPIKey provides a mock function with given fields: ctx, params
func (_m *APIKeyService) RevokeAPIKey(ctx context.Context, params services.RevokeKeyParams) (*dtos.RevokedKeyInfo, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAPIKey")
	}

	var r0 *dtos.RevokedKeyInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.RevokeKeyParams) (*dtos.RevokedKeyInfo, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.RevokeKeyParams) *dtos.RevokedKeyInfo); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.RevokedKeyInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.RevokeKeyParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAPIKey provides a mock function with given fields: ctx, rawKey
func (_m *APIKeyService) ValidateAPIKey(ctx context.Context, rawKey string) (*services.ValidatedKey, error) {
	ret := _m.Called(ctx, rawKey)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAPIKey")
	}

	var r0 *services.ValidatedKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*services.ValidatedKey, error)); ok {
		return rf(ctx, rawKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *services.ValidatedKey); ok {
		r0 = rf(ctx, rawKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ValidatedKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPIKeyService creates a new instance of APIKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIKeyService {
	mock := &APIKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
