// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/NIROOZbx/notification-engine/internal/dtos"
	jwt "github.com/NIROOZbx/notification-engine/pkg/jwt"

	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"

	sqlc "github.com/NIROOZbx/notification-engine/db/sqlc"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// CompleteOnboarding provides a mock function with given fields: ctx, userID, workspaceName
func (_m *AuthService) CompleteOnboarding(ctx context.Context, userID pgtype.UUID, workspaceName string) (*dtos.AuthResponse, *jwt.Pair, error) {
	ret := _m.Called(ctx, userID, workspaceName)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOnboarding")
	}

	var r0 *dtos.AuthResponse
	var r1 *jwt.Pair
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) (*dtos.AuthResponse, *jwt.Pair, error)); ok {
		return rf(ctx, userID, workspaceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) *dtos.AuthResponse); ok {
		r0 = rf(ctx, userID, workspaceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, string) *jwt.Pair); ok {
		r1 = rf(ctx, userID, workspaceName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*jwt.Pair)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, pgtype.UUID, string) error); ok {
		r2 = rf(ctx, userID, workspaceName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *AuthService) FindUserByEmail(ctx context.Context, email string) (*sqlc.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sqlc.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sqlc.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleOAuthCallback provides a mock function with given fields: ctx, user
func (_m *AuthService) HandleOAuthCallback(ctx context.Context, user *dtos.OAuthUserDetails) (*dtos.AuthResponse, *jwt.Pair, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for HandleOAuthCallback")
	}

	var r0 *dtos.AuthResponse
	var r1 *jwt.Pair
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.OAuthUserDetails) (*dtos.AuthResponse, *jwt.Pair, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.OAuthUserDetails) *dtos.AuthResponse); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.OAuthUserDetails) *jwt.Pair); ok {
		r1 = rf(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*jwt.Pair)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dtos.OAuthUserDetails) error); ok {
		r2 = rf(ctx, user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Login provides a mock function with given fields: ctx, req
func (_m *AuthService) Login(ctx context.Context, req dtos.LoginRequest) (*dtos.AuthResponse, *jwt.Pair, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dtos.AuthResponse
	var r1 *jwt.Pair
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.LoginRequest) (*dtos.AuthResponse, *jwt.Pair, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.LoginRequest) *dtos.AuthResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.LoginRequest) *jwt.Pair); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*jwt.Pair)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, dtos.LoginRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Logout provides a mock function with given fields: ctx, userID, refreshToken
func (_m *AuthService) Logout(ctx context.Context, userID pgtype.UUID, refreshToken string) error {
	ret := _m.Called(ctx, userID, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) error); ok {
		r0 = rf(ctx, userID, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: ctx, req
func (_m *AuthService) Register(ctx context.Context, req dtos.RegisterRequest) (*sqlc.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RegisterRequest) (*sqlc.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.RegisterRequest) *sqlc.User); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyEmail provides a mock function with given fields: ctx, token
func (_m *AuthService) VerifyEmail(ctx context.Context, token string) (*dtos.AuthResponse, *jwt.Pair, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 *dtos.AuthResponse
	var r1 *jwt.Pair
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dtos.AuthResponse, *jwt.Pair, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dtos.AuthResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *jwt.Pair); ok {
		r1 = rf(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*jwt.Pair)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, token)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
