// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	billing "github.com/NIROOZbx/notification-engine/internal/billing"

	mock "github.com/stretchr/testify/mock"
)

// BillingService is an autogenerated mock type for the BillingService type
type BillingService struct {
	mock.Mock
}

// CancelSubscription provides a mock function with given fields: ctx, workspaceID, subscriptionID
func (_m *BillingService) CancelSubscription(ctx context.Context, workspaceID string, subscriptionID string) error {
	ret := _m.Called(ctx, workspaceID, subscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for CancelSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, workspaceID, subscriptionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCheckoutSession provides a mock function with given fields: ctx, workspaceID, planID, customerEmail
func (_m *BillingService) CreateCheckoutSession(ctx context.Context, workspaceID string, planID string, customerEmail string) (string, error) {
	ret := _m.Called(ctx, workspaceID, planID, customerEmail)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, workspaceID, planID, customerEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, workspaceID, planID, customerEmail)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, planID, customerEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCheckoutSession provides a mock function with given fields: ctx, sessionID
func (_m *BillingService) GetCheckoutSession(ctx context.Context, sessionID string) (*billing.CheckoutSessionDetails, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutSession")
	}

	var r0 *billing.CheckoutSessionDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*billing.CheckoutSessionDetails, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.CheckoutSessionDetails); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.CheckoutSessionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscription provides a mock function with given fields: ctx, workspaceID
func (_m *BillingService) GetSubscription(ctx context.Context, workspaceID string) (*billing.SubscriptionResponse, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 *billing.SubscriptionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*billing.SubscriptionResponse, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.SubscriptionResponse); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.SubscriptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsage provides a mock function with given fields: ctx, workspaceID, environmentID
func (_m *BillingService) GetUsage(ctx context.Context, workspaceID string, environmentID string) (*billing.UsageResponse, error) {
	ret := _m.Called(ctx, workspaceID, environmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsage")
	}

	var r0 *billing.UsageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*billing.UsageResponse, error)); ok {
		return rf(ctx, workspaceID, environmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *billing.UsageResponse); ok {
		r0 = rf(ctx, workspaceID, environmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.UsageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, environmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBillingService creates a new instance of BillingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingService {
	mock := &BillingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
