// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// ChannelConfigService is an autogenerated mock type for the ChannelConfigService type
type ChannelConfigService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *ChannelConfigService) Create(ctx context.Context, params domain.CreateChannelConfigParams) (*domain.ChannelConfig, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.ChannelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateChannelConfigParams) (*domain.ChannelConfig, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateChannelConfigParams) *domain.ChannelConfig); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ChannelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateChannelConfigParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteChannelConfig provides a mock function with given fields: ctx, id, workspaceID
func (_m *ChannelConfigService) DeleteChannelConfig(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChannelConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChannelConfigByID provides a mock function with given fields: ctx, id, workspaceID
func (_m *ChannelConfigService) GetChannelConfigByID(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) (*domain.ChannelConfig, error) {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelConfigByID")
	}

	var r0 *domain.ChannelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) (*domain.ChannelConfig, error)); ok {
		return rf(ctx, id, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) *domain.ChannelConfig); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ChannelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, id, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDefaultChannelConfig provides a mock function with given fields: ctx, workspaceID, channel
func (_m *ChannelConfigService) GetDefaultChannelConfig(ctx context.Context, workspaceID pgtype.UUID, channel string) (*domain.ChannelConfig, error) {
	ret := _m.Called(ctx, workspaceID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultChannelConfig")
	}

	var r0 *domain.ChannelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) (*domain.ChannelConfig, error)); ok {
		return rf(ctx, workspaceID, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) *domain.ChannelConfig); ok {
		r0 = rf(ctx, workspaceID, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ChannelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, string) error); ok {
		r1 = rf(ctx, workspaceID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, workspaceID
func (_m *ChannelConfigService) List(ctx context.Context, workspaceID pgtype.UUID) ([]*domain.ChannelConfig, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.ChannelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]*domain.ChannelConfig, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []*domain.ChannelConfig); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ChannelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetChannelConfigDefault provides a mock function with given fields: ctx, id, workspaceID
func (_m *ChannelConfigService) SetChannelConfigDefault(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for SetChannelConfigDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateChannelConfig provides a mock function with given fields: ctx, params
func (_m *ChannelConfigService) UpdateChannelConfig(ctx context.Context, params domain.UpdateChannelConfigParams) (*domain.ChannelConfig, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChannelConfig")
	}

	var r0 *domain.ChannelConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateChannelConfigParams) (*domain.ChannelConfig, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateChannelConfigParams) *domain.ChannelConfig); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ChannelConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateChannelConfigParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewChannelConfigService creates a new instance of ChannelConfigService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelConfigService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelConfigService {
	mock := &ChannelConfigService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
