// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// LayoutService is an autogenerated mock type for the LayoutService type
type LayoutService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *LayoutService) Create(ctx context.Context, params domain.CreateLayoutParams) (*domain.Layout, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateLayoutParams) (*domain.Layout, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateLayoutParams) *domain.Layout); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateLayoutParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, workspaceID
func (_m *LayoutService) Delete(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id, workspaceID
func (_m *LayoutService) GetByID(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) (*domain.Layout, error) {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) (*domain.Layout, error)); ok {
		return rf(ctx, id, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) *domain.Layout); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, id, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, workspaceID
func (_m *LayoutService) List(ctx context.Context, workspaceID pgtype.UUID) ([]*domain.Layout, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]*domain.Layout, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []*domain.Layout); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDefault provides a mock function with given fields: ctx, id, workspaceID
func (_m *LayoutService) SetDefault(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for SetDefault")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, params
func (_m *LayoutService) Update(ctx context.Context, params domain.UpdateLayoutParams) (*domain.Layout, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Layout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateLayoutParams) (*domain.Layout, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateLayoutParams) *domain.Layout); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Layout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateLayoutParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLayoutService creates a new instance of LayoutService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLayoutService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LayoutService {
	mock := &LayoutService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
