// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/NIROOZbx/notification-engine/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// PlanService is an autogenerated mock type for the PlanService type
type PlanService struct {
	mock.Mock
}

// GetAllPlans provides a mock function with given fields: ctx
func (_m *PlanService) GetAllPlans(ctx context.Context) ([]services.PlanResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPlans")
	}

	var r0 []services.PlanResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]services.PlanResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []services.PlanResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.PlanResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlanService creates a new instance of PlanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlanService {
	mock := &PlanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
