// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	services "github.com/NIROOZbx/notification-engine/internal/services"
)

// SubscriberService is an autogenerated mock type for the SubscriberService type
type SubscriberService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id, workspaceID
func (_m *SubscriberService) Delete(ctx context.Context, id string, workspaceID string) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPreferencesByExternalID provides a mock function with given fields: ctx, workspaceID, environmentID, externalUserID
func (_m *SubscriberService) GetPreferencesByExternalID(ctx context.Context, workspaceID string, environmentID string, externalUserID string) ([]*domain.UserPreference, error) {
	ret := _m.Called(ctx, workspaceID, environmentID, externalUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreferencesByExternalID")
	}

	var r0 []*domain.UserPreference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*domain.UserPreference, error)); ok {
		return rf(ctx, workspaceID, environmentID, externalUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []*domain.UserPreference); ok {
		r0 = rf(ctx, workspaceID, environmentID, externalUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserPreference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, environmentID, externalUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Identify provides a mock function with given fields: ctx, input
func (_m *SubscriberService) Identify(ctx context.Context, input services.IdentifySubscriberInput) ([]*domain.Subscriber, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Identify")
	}

	var r0 []*domain.Subscriber
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.IdentifySubscriberInput) ([]*domain.Subscriber, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.IdentifySubscriberInput) []*domain.Subscriber); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Subscriber)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.IdentifySubscriberInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, workspaceID, environmentID, page, pageSize
func (_m *SubscriberService) List(ctx context.Context, workspaceID string, environmentID string, page int32, pageSize int32) (*domain.SubscriberList, error) {
	ret := _m.Called(ctx, workspaceID, environmentID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.SubscriberList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, int32) (*domain.SubscriberList, error)); ok {
		return rf(ctx, workspaceID, environmentID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, int32) *domain.SubscriberList); ok {
		r0 = rf(ctx, workspaceID, environmentID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SubscriberList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int32, int32) error); ok {
		r1 = rf(ctx, workspaceID, environmentID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertPreference provides a mock function with given fields: ctx, input
func (_m *SubscriberService) UpsertPreference(ctx context.Context, input services.UpsertPreferenceInput) (*domain.UserPreference, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPreference")
	}

	var r0 *domain.UserPreference
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.UpsertPreferenceInput) (*domain.UserPreference, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.UpsertPreferenceInput) *domain.UserPreference); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPreference)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.UpsertPreferenceInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriberService creates a new instance of SubscriberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriberService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriberService {
	mock := &SubscriberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
