// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/NIROOZbx/notification-engine/internal/domain"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// TemplateService is an autogenerated mock type for the TemplateService type
type TemplateService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *TemplateService) Create(ctx context.Context, params domain.CreateTemplateParams) (*domain.Template, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateParams) (*domain.Template, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateParams) *domain.Template); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateTemplateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateChannel provides a mock function with given fields: ctx, params
func (_m *TemplateService) CreateChannel(ctx context.Context, params domain.CreateTemplateChannelParams) (*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 *domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateChannelParams) (*domain.TemplateChannel, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateTemplateChannelParams) *domain.TemplateChannel); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateTemplateChannelParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, workspaceID
func (_m *TemplateService) Delete(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteChannel provides a mock function with given fields: ctx, id, templateID, workspaceID
func (_m *TemplateService) DeleteChannel(ctx context.Context, id pgtype.UUID, templateID pgtype.UUID, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, id, templateID, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID, pgtype.UUID) error); ok {
		r0 = rf(ctx, id, templateID, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id, workspaceID
func (_m *TemplateService) GetByID(ctx context.Context, id pgtype.UUID, workspaceID pgtype.UUID) (*domain.Template, error) {
	ret := _m.Called(ctx, id, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) (*domain.Template, error)); ok {
		return rf(ctx, id, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) *domain.Template); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, id, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, workspaceID, envID
func (_m *TemplateService) List(ctx context.Context, workspaceID pgtype.UUID, envID pgtype.UUID) ([]*domain.Template, error) {
	ret := _m.Called(ctx, workspaceID, envID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) ([]*domain.Template, error)); ok {
		return rf(ctx, workspaceID, envID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) []*domain.Template); ok {
		r0 = rf(ctx, workspaceID, envID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID, envID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListChannels provides a mock function with given fields: ctx, templateID, workspaceID
func (_m *TemplateService) ListChannels(ctx context.Context, templateID pgtype.UUID, workspaceID pgtype.UUID) ([]*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, templateID, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for ListChannels")
	}

	var r0 []*domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) ([]*domain.TemplateChannel, error)); ok {
		return rf(ctx, templateID, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) []*domain.TemplateChannel); ok {
		r0 = rf(ctx, templateID, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, templateID, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, params
func (_m *TemplateService) Update(ctx context.Context, params domain.UpdateTemplateParams) (*domain.Template, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateParams) (*domain.Template, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateParams) *domain.Template); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateTemplateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChannel provides a mock function with given fields: ctx, params
func (_m *TemplateService) UpdateChannel(ctx context.Context, params domain.UpdateTemplateChannelParams) (*domain.TemplateChannel, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChannel")
	}

	var r0 *domain.TemplateChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateChannelParams) (*domain.TemplateChannel, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTemplateChannelParams) *domain.TemplateChannel); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TemplateChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateTemplateChannelParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTemplateService creates a new instance of TemplateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTemplateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TemplateService {
	mock := &TemplateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
