// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	services "github.com/NIROOZbx/notification-engine/internal/services"

	sqlc "github.com/NIROOZbx/notification-engine/db/sqlc"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, params
func (_m *UserService) CreateUser(ctx context.Context, params services.CreateUser) (*sqlc.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateUser) (*sqlc.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.CreateUser) *sqlc.User); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.CreateUser) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserService) FindUserByEmail(ctx context.Context, email string) (*sqlc.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sqlc.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sqlc.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByID provides a mock function with given fields: ctx, id
func (_m *UserService) FindUserByID(ctx context.Context, id pgtype.UUID) (*sqlc.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*sqlc.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *sqlc.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByProviderID provides a mock function with given fields: ctx, provider, providerID
func (_m *UserService) FindUserByProviderID(ctx context.Context, provider string, providerID string) (*sqlc.User, error) {
	ret := _m.Called(ctx, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByProviderID")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*sqlc.User, error)); ok {
		return rf(ctx, provider, providerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *sqlc.User); ok {
		r0 = rf(ctx, provider, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, providerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthContextByEmail provides a mock function with given fields: ctx, email
func (_m *UserService) GetAuthContextByEmail(ctx context.Context, email string) (*sqlc.GetAuthContextByEmailRow, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthContextByEmail")
	}

	var r0 *sqlc.GetAuthContextByEmailRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sqlc.GetAuthContextByEmailRow, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sqlc.GetAuthContextByEmailRow); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.GetAuthContextByEmailRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFullUserDetails provides a mock function with given fields: ctx, userID
func (_m *UserService) GetFullUserDetails(ctx context.Context, userID pgtype.UUID) (*sqlc.GetUserWithWorkspaceRow, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFullUserDetails")
	}

	var r0 *sqlc.GetUserWithWorkspaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*sqlc.GetUserWithWorkspaceRow, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *sqlc.GetUserWithWorkspaceRow); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.GetUserWithWorkspaceRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkUserAsVerified provides a mock function with given fields: ctx, id
func (_m *UserService) MarkUserAsVerified(ctx context.Context, id pgtype.UUID) (*sqlc.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUserAsVerified")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*sqlc.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *sqlc.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertOAuthUser provides a mock function with given fields: ctx, input
func (_m *UserService) UpsertOAuthUser(ctx context.Context, input services.UpsertOAuthInput) (*sqlc.User, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOAuthUser")
	}

	var r0 *sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.UpsertOAuthInput) (*sqlc.User, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.UpsertOAuthInput) *sqlc.User); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.UpsertOAuthInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
