// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/NIROOZbx/notification-engine/internal/dtos"
	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"

	services "github.com/NIROOZbx/notification-engine/internal/services"
)

// WorkspaceService is an autogenerated mock type for the WorkspaceService type
type WorkspaceService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, workspaceID
func (_m *WorkspaceService) Delete(ctx context.Context, workspaceID pgtype.UUID) error {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, workspaceID
func (_m *WorkspaceService) GetByID(ctx context.Context, workspaceID pgtype.UUID) (*dtos.WorkspaceResponse, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *dtos.WorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*dtos.WorkspaceResponse, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *dtos.WorkspaceResponse); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.WorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *WorkspaceService) GetBySlug(ctx context.Context, slug string) (*dtos.WorkspaceResponse, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *dtos.WorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dtos.WorkspaceResponse, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dtos.WorkspaceResponse); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.WorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMemberRole provides a mock function with given fields: ctx, workspaceID, userID
func (_m *WorkspaceService) GetMemberRole(ctx context.Context, workspaceID pgtype.UUID, userID pgtype.UUID) (string, error) {
	ret := _m.Called(ctx, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) (string, error)); ok {
		return rf(ctx, workspaceID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, pgtype.UUID) string); ok {
		r0 = rf(ctx, workspaceID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMembers provides a mock function with given fields: ctx, workspaceID
func (_m *WorkspaceService) GetMembers(ctx context.Context, workspaceID pgtype.UUID) ([]dtos.WorkspaceMemberResponse, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []dtos.WorkspaceMemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]dtos.WorkspaceMemberResponse, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []dtos.WorkspaceMemberResponse); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dtos.WorkspaceMemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrCreate provides a mock function with given fields: ctx, userID, name
func (_m *WorkspaceService) GetOrCreate(ctx context.Context, userID pgtype.UUID, name string) (*services.WorkspaceWithRole, error) {
	ret := _m.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *services.WorkspaceWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) (*services.WorkspaceWithRole, error)); ok {
		return rf(ctx, userID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) *services.WorkspaceWithRole); ok {
		r0 = rf(ctx, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.WorkspaceWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, string) error); ok {
		r1 = rf(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkspaceMemberByUserID provides a mock function with given fields: ctx, userID
func (_m *WorkspaceService) GetWorkspaceMemberByUserID(ctx context.Context, userID pgtype.UUID) (*dtos.WorkspaceMemberResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspaceMemberByUserID")
	}

	var r0 *dtos.WorkspaceMemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (*dtos.WorkspaceMemberResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) *dtos.WorkspaceMemberResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.WorkspaceMemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: ctx, params
func (_m *WorkspaceService) RemoveMember(ctx context.Context, params services.RemoveMemberParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.RemoveMemberParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMemberRole provides a mock function with given fields: ctx, params
func (_m *WorkspaceService) UpdateMemberRole(ctx context.Context, params services.UpdateMemberRoleParams) (*dtos.WorkspaceMemberResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 *dtos.WorkspaceMemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.UpdateMemberRoleParams) (*dtos.WorkspaceMemberResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.UpdateMemberRoleParams) *dtos.WorkspaceMemberResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.WorkspaceMemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.UpdateMemberRoleParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateName provides a mock function with given fields: ctx, workspaceID, name
func (_m *WorkspaceService) UpdateName(ctx context.Context, workspaceID pgtype.UUID, name string) (*dtos.WorkspaceResponse, error) {
	ret := _m.Called(ctx, workspaceID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateName")
	}

	var r0 *dtos.WorkspaceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) (*dtos.WorkspaceResponse, error)); ok {
		return rf(ctx, workspaceID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID, string) *dtos.WorkspaceResponse); ok {
		r0 = rf(ctx, workspaceID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.WorkspaceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID, string) error); ok {
		r1 = rf(ctx, workspaceID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWorkspaceService creates a new instance of WorkspaceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkspaceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkspaceService {
	mock := &WorkspaceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
